/**
 * Constitutional Asset Register — Article VII / FRAMEWORK-IAR-001
 */

import type { InstitutionalAsset } from "@/lib/institutional-assets/types";

export const ASSET_REGISTRY_IDENTIFIER = "FRAMEWORK-IAR-001";

export const INSTITUTIONAL_ASSETS: InstitutionalAsset[] = [
  {
    assetId: "IAR-CONST-001",
    slug: "volume-i-constitution",
    name: "Volume I — The Stankings Group Constitution",
    category: "constitutional",
    categoryLabel: "The Constitution",
    description:
      "Supreme internal governing law — Articles I–XVII and constitutional frameworks implementing the Canons.",
    owningInstitution: "Stankings Group",
    steward: "Library Council",
    constitutionArticle: "Art. VII § 7.02",
    canonReferences: ["CANON-007", "CANON-023", "CANON-025"],
    criticality: "critical",
    securityClassification: "internal",
    backupStatus: "verified",
    recoveryObjective: "RPO 0 — version-controlled in Library and git; multiple custodian copies",
    dependencies: ["Volume 0 Canons", "IKI", "Supabase knowledge store"],
    annualReviewDate: "2031-06-27",
    riskAssessment: "Low — active development; Constitutional Congress review planned before v1.0 seal",
    knowledgeObjects: [
      { title: "CONSTITUTION-ARTICLE-VII", href: "/library/constitution/article-vii" },
      { title: "Constitution Portal", href: "/library/constitution" },
    ],
    dashboardTags: ["critical", "knowledge"],
    status: "active",
  },
  {
    assetId: "IAR-CANON-001",
    slug: "volume-zero-canons",
    name: "Volume 0 — The Stankings Canons",
    category: "constitutional",
    categoryLabel: "The Stankings Canons",
    description: "Twenty-five philosophical principles — foundation interpreted by, not superseded by, the Constitution.",
    owningInstitution: "Stankings Group",
    steward: "Library Council",
    constitutionArticle: "Art. VII § 7.02",
    canonReferences: ["CANON-025", "CANON-023"],
    criticality: "critical",
    securityClassification: "public",
    backupStatus: "verified",
    recoveryObjective: "RPO 0 — sealed v1.0; Canon Maturity Dashboard tracks application",
    dependencies: ["Constitution Volume I", "Custodian Programme"],
    annualReviewDate: "2031-06-27",
    riskAssessment: "Low — sealed at v1.0; deliberate maturity cap enforced",
    knowledgeObjects: [
      { title: "Volume 0", href: "/library/first-principles" },
      { title: "FRAMEWORK-CMD-001", href: "/library/canon-maturity" },
    ],
    dashboardTags: ["critical", "knowledge", "brand"],
    status: "active",
  },
  {
    assetId: "IAR-LIB-001",
    slug: "stankings-library-iki",
    name: "The Stankings Library / IKI",
    category: "knowledge",
    categoryLabel: "The Stankings Library",
    description:
      "Institutional Knowledge Infrastructure — Library, lexicon, graph, frameworks, and constitutional portals.",
    owningInstitution: "The Stankings Institute",
    steward: "Library Council",
    constitutionArticle: "Art. VII § 7.05",
    canonReferences: ["CANON-021", "CANON-009", "CANON-007"],
    criticality: "critical",
    securityClassification: "internal",
    backupStatus: "verified",
    recoveryObjective: "RPO 24h — git, Supabase migrations, seed knowledge objects",
    dependencies: ["LS-001", "LS-002", "Supabase", "Next.js platform"],
    annualReviewDate: "2027-06-27",
    riskAssessment: "Medium — growing surface area; dependency on platform health",
    knowledgeObjects: [
      { title: "LS-001", href: "/library/standards/ls-001" },
      { title: "FRAMEWORK-IKG-001", href: "/library/knowledge-graph" },
      { title: "IDR-IKI-001", href: "/library/decisions/IDR-IKI-001" },
    ],
    dashboardTags: ["critical", "knowledge", "technology", "recovery"],
    status: "active",
  },
  {
    assetId: "IAR-TRUST-001",
    slug: "public-trust-commitment-registry",
    name: "Public Trust & Commitment Registry",
    category: "trust",
    categoryLabel: "Public trust",
    description:
      "Institutional credibility managed with the same discipline as financial assets — commitments, trust impact, and reputation.",
    owningInstitution: "Stankings Group",
    steward: "Board of Directors (forming)",
    constitutionArticle: "Art. VII § 7.05",
    canonReferences: ["CANON-002", "CANON-014"],
    criticality: "critical",
    securityClassification: "confidential",
    backupStatus: "partial",
    recoveryObjective: "RTO 48h — commitment records and trust assessments preserved in Library",
    dependencies: ["FRAMEWORK-TIA-001", "Commitment Registry", "Incident Center"],
    annualReviewDate: "2027-06-27",
    riskAssessment: "High sensitivity — loss of trust is material institutional event per Art. VII § 7.05",
    knowledgeObjects: [
      { title: "FRAMEWORK-TIA-001", href: "/library/frameworks/trust-impact-assessment" },
      { title: "Commitment Registry", href: "/library/commitments" },
      { title: "CANON-002", href: "/library/canon/CANON-002" },
    ],
    dashboardTags: ["critical", "trust"],
    status: "active",
  },
  {
    assetId: "IAR-KNOW-001",
    slug: "institutional-knowledge-graph",
    name: "Institutional Knowledge Graph",
    category: "knowledge",
    categoryLabel: "Institutional knowledge",
    description: "Living map of Canons, frameworks, companies, systems, and constitutional relationships.",
    owningInstitution: "The Stankings Institute",
    steward: "Library Council",
    constitutionArticle: "Art. XIII § 13.02",
    canonReferences: ["CANON-021", "CANON-009"],
    criticality: "high",
    securityClassification: "internal",
    backupStatus: "verified",
    recoveryObjective: "RPO 0 — graph.ts and seed synchronized with Library",
    dependencies: ["IKI", "Library Engine", "All Knowledge Objects"],
    annualReviewDate: "2027-06-27",
    riskAssessment: "Low — actively maintained with each constitutional adoption",
    knowledgeObjects: [
      { title: "FRAMEWORK-SLP-001", href: "/library/stankings-library" },
      { title: "FRAMEWORK-IKG-001", href: "/library/frameworks/institutional-knowledge-graph" },
      { title: "Knowledge Graph", href: "/library/knowledge-graph" },
    ],
    dashboardTags: ["knowledge", "technology"],
    status: "active",
  },
  {
    assetId: "IAR-TECH-001",
    slug: "yike-passport-trust-graph",
    name: "Yike Passport Trust Graph",
    category: "technology",
    categoryLabel: "Trust infrastructure",
    description: "Digital identity and verification trust infrastructure — Passport, verification, and trust graph.",
    owningInstitution: "Yike",
    steward: "Yike Platform Team (forming)",
    constitutionArticle: "Art. XII § 12.05",
    canonReferences: ["CANON-002", "CANON-012"],
    criticality: "critical",
    securityClassification: "restricted",
    backupStatus: "planned",
    recoveryObjective: "RTO 4h — identity continuity critical for ecosystem trust",
    dependencies: ["Verification capability", "Platform Registry", "Security credentials"],
    annualReviewDate: "2027-06-27",
    riskAssessment: "High — trust-sensitive; cyber resilience priority",
    knowledgeObjects: [
      { title: "Yike", href: "/companies/yike" },
      { title: "Constitutional Trust Centre", href: "/library/constitutional-trust" },
      { title: "Platform Registry", href: "/library/platforms" },
    ],
    dashboardTags: ["critical", "technology", "trust", "cyber", "recovery"],
    status: "forming",
  },
  {
    assetId: "IAR-AI-001",
    slug: "institutional-ai-systems",
    name: "Institutional AI Systems",
    category: "ai",
    categoryLabel: "Artificial intelligence systems",
    description: "AI used for constitutional explanation, decision support, and institutional operations — governed responsibly.",
    owningInstitution: "Stankings Group",
    steward: "Engineering Leadership (forming)",
    constitutionArticle: "Art. XII § 12.06",
    canonReferences: ["CANON-007", "CANON-010", "CANON-013"],
    criticality: "high",
    securityClassification: "confidential",
    backupStatus: "partial",
    recoveryObjective: "RTO 24h — model configs and prompts version-controlled",
    dependencies: ["IKI", "Library content", "Security credentials"],
    annualReviewDate: "2027-06-27",
    riskAssessment: "Medium — innovation governance required per CANON-013",
    knowledgeObjects: [
      { title: "FRAMEWORK-IGF-001", href: "/library/frameworks/innovation-governance" },
      { title: "Constitutional Trust Centre", href: "/library/constitutional-trust" },
      { title: "Institutional AI", href: "/library/constitution" },
    ],
    dashboardTags: ["ai", "technology", "cyber"],
    status: "forming",
  },
  {
    assetId: "IAR-BRAND-001",
    slug: "stankings-brand-identity",
    name: "Stankings Group Brand Identity",
    category: "brand",
    categoryLabel: "Brand identity",
    description: "Legacy Gold palette, institutional voice, and public reputation across the ecosystem.",
    owningInstitution: "Stankings Group",
    steward: "Library Council",
    constitutionArticle: "Art. VII § 7.02",
    canonReferences: ["CANON-002", "CANON-024"],
    criticality: "high",
    securityClassification: "public",
    backupStatus: "verified",
    recoveryObjective: "RPO 0 — design system in institutional.ts and Library standards",
    dependencies: ["Institutional Identity Statements", "Volume 0 Canons"],
    annualReviewDate: "2027-06-27",
    riskAssessment: "Low — documented; reputation protected through trust governance",
    knowledgeObjects: [
      { title: "FRAMEWORK-IIS-001", href: "/library/frameworks/institutional-identity-statement" },
      { title: "Institutional Identity", href: "/library/institutional-identity" },
    ],
    dashboardTags: ["brand", "trust"],
    status: "active",
  },
  {
    assetId: "IAR-DATA-001",
    slug: "stankings-lexicon",
    name: "The Stankings Lexicon (LS-002)",
    category: "data",
    categoryLabel: "Data",
    description: "Authoritative institutional vocabulary — all terms defined before use in Library volumes.",
    owningInstitution: "The Stankings Institute",
    steward: "Library Council",
    constitutionArticle: "Art. VII § 7.05",
    canonReferences: ["CANON-007", "CANON-021"],
    criticality: "high",
    securityClassification: "internal",
    backupStatus: "verified",
    recoveryObjective: "RPO 0 — lexicon-engine seed version-controlled",
    dependencies: ["LS-001", "Library Engine"],
    annualReviewDate: "2027-06-27",
    riskAssessment: "Low — Editor-in-Chief Decision No. 3 enforced in institutional rules",
    knowledgeObjects: [
      { title: "LS-002", href: "/library/standards/ls-002" },
      { title: "Lexicon", href: "/library/lexicon" },
    ],
    dashboardTags: ["knowledge", "recovery"],
    status: "active",
  },
  {
    assetId: "IAR-SEC-001",
    slug: "security-infrastructure",
    name: "Security Credentials & Infrastructure",
    category: "technology",
    categoryLabel: "Security credentials",
    description: "Platform security, credentials, cyber resilience, and disaster recovery for digital assets.",
    owningInstitution: "Stankings Group",
    steward: "Engineering Leadership (forming)",
    constitutionArticle: "Art. VII § 7.06",
    canonReferences: ["CANON-015", "CANON-007"],
    criticality: "critical",
    securityClassification: "restricted",
    backupStatus: "planned",
    recoveryObjective: "RTO 4h / RPO 1h for production systems",
    dependencies: ["Supabase", "Vercel/hosting", "Yike Passport", "BayRight Escrow"],
    annualReviewDate: "2027-06-27",
    riskAssessment: "High — forming; cyber resilience programme required",
    knowledgeObjects: [
      { title: "Incident Center", href: "/library/incidents" },
      { title: "FRAMEWORK-IIAF-001", href: "/library/frameworks/incident-accountability" },
    ],
    dashboardTags: ["critical", "technology", "cyber", "recovery"],
    status: "forming",
  },
];

export function getInstitutionalAsset(slug: string): InstitutionalAsset | undefined {
  return INSTITUTIONAL_ASSETS.find((a) => a.slug === slug);
}

export function getAssetsByDashboardTag(tag: string): InstitutionalAsset[] {
  return INSTITUTIONAL_ASSETS.filter((a) => a.dashboardTags.includes(tag));
}

export function getAssetRegistryStats() {
  const total = INSTITUTIONAL_ASSETS.length;
  const critical = INSTITUTIONAL_ASSETS.filter((a) => a.criticality === "critical").length;
  const trust = getAssetsByDashboardTag("trust").length;
  const knowledge = getAssetsByDashboardTag("knowledge").length;
  const recoveryReady = INSTITUTIONAL_ASSETS.filter(
    (a) => a.backupStatus === "verified" || a.backupStatus === "partial",
  ).length;
  return { total, critical, trust, knowledge, recoveryReady };
}
