/**
 * Institutional Knowledge Graph — connected knowledge for intelligent search
 */

export interface GraphNode {
  id: string;
  label: string;
  type: "term" | "canon" | "framework" | "volume" | "company" | "capability" | "system";
  href?: string;
}

export interface GraphEdge {
  from: string;
  to: string;
  relationship:
    | "defines"
    | "supports"
    | "depends_on"
    | "references"
    | "implements"
    | "applied_in"
    | "conforms_to"
    | "part_of"
    | "enforces"
    | "includes"
    | "aliases"
    | "supersedes";
}

export const INSTITUTIONAL_GRAPH_NODES: GraphNode[] = [
  { id: "trust", label: "Trust", type: "term", href: "/library/lexicon/trust" },
  { id: "CANON-002", label: "CANON-002", type: "canon", href: "/library/canon/CANON-002" },
  { id: "CANON-003", label: "CANON-003", type: "canon", href: "/library/canon/CANON-003" },
  { id: "CANON-004", label: "CANON-004", type: "canon", href: "/library/canon/CANON-004" },
  { id: "CANON-005", label: "CANON-005", type: "canon", href: "/library/canon/CANON-005" },
  { id: "CANON-006", label: "CANON-006", type: "canon", href: "/library/canon/CANON-006" },
  { id: "CANON-007", label: "CANON-007", type: "canon", href: "/library/canon/CANON-007" },
  { id: "CANON-008", label: "CANON-008", type: "canon", href: "/library/canon/CANON-008" },
  { id: "CANON-009", label: "CANON-009", type: "canon", href: "/library/canon/CANON-009" },
  { id: "CANON-010", label: "CANON-010", type: "canon", href: "/library/canon/CANON-010" },
  { id: "CANON-011", label: "CANON-011", type: "canon", href: "/library/canon/CANON-011" },
  { id: "CANON-012", label: "CANON-012", type: "canon", href: "/library/canon/CANON-012" },
  { id: "CANON-013", label: "CANON-013", type: "canon", href: "/library/canon/CANON-013" },
  { id: "CANON-014", label: "CANON-014", type: "canon", href: "/library/canon/CANON-014" },
  { id: "CANON-015", label: "CANON-015", type: "canon", href: "/library/canon/CANON-015" },
  { id: "CANON-016", label: "CANON-016", type: "canon", href: "/library/canon/CANON-016" },
  { id: "CANON-017", label: "CANON-017", type: "canon", href: "/library/canon/CANON-017" },
  { id: "CANON-018", label: "CANON-018", type: "canon", href: "/library/canon/CANON-018" },
  { id: "CANON-019", label: "CANON-019", type: "canon", href: "/library/canon/CANON-019" },
  { id: "CANON-020", label: "CANON-020", type: "canon", href: "/library/canon/CANON-020" },
  { id: "CANON-021", label: "CANON-021", type: "canon", href: "/library/canon/CANON-021" },
  { id: "CANON-022", label: "CANON-022", type: "canon", href: "/library/canon/CANON-022" },
  { id: "CANON-023", label: "CANON-023", type: "canon", href: "/library/canon/CANON-023" },
  { id: "CANON-024", label: "CANON-024", type: "canon", href: "/library/canon/CANON-024" },
  { id: "CANON-025", label: "CANON-025", type: "canon", href: "/library/canon/CANON-025" },
  { id: "CANON-001", label: "CANON-001", type: "canon", href: "/library/canon/CANON-001" },
  { id: "ecosystem-map", label: "Ecosystem Map", type: "volume", href: "/library/ecosystem" },
  { id: "custodian-programme", label: "Custodian Programme", type: "volume", href: "/library/custodian-programme" },
  { id: "constitution", label: "Constitution v1.0", type: "volume", href: "/library/constitution" },
  { id: "institutional-identity", label: "Institutional Identity", type: "system", href: "/library/institutional-identity" },
  { id: "CONSTITUTION-ARTICLE-I", label: "Article I", type: "framework", href: "/library/constitution/article-i" },
  { id: "FRAMEWORK-IIS-001", label: "IIS Framework", type: "framework", href: "/library/frameworks/institutional-identity-statement" },
  { id: "CONSTITUTION-ARTICLE-II", label: "Article II", type: "framework", href: "/library/constitution/article-ii" },
  { id: "FRAMEWORK-CAE-001", label: "CAE", type: "framework", href: "/library/frameworks/constitutional-alignment-engine" },
  { id: "constitutional-alignment", label: "Constitutional Alignment", type: "system", href: "/library/constitutional-alignment" },
  { id: "CONSTITUTION-ARTICLE-III", label: "Article III", type: "framework", href: "/library/constitution/article-iii" },
  { id: "FRAMEWORK-STEWARDSHIP-PORTAL-001", label: "Stewardship Portal", type: "framework", href: "/library/frameworks/stewardship-portal" },
  { id: "stewardship-portal", label: "Stewardship Profiles", type: "system", href: "/library/stewardship" },
  { id: "CONSTITUTION-ARTICLE-IV", label: "Article IV", type: "framework", href: "/library/constitution/article-iv" },
  { id: "FRAMEWORK-CGOV-001", label: "CGOV", type: "framework", href: "/library/frameworks/constitutional-governance-portal" },
  { id: "constitutional-governance", label: "Constitutional Governance", type: "system", href: "/library/governance" },
  { id: "CONSTITUTION-ARTICLE-V", label: "Article V", type: "framework", href: "/library/constitution/article-v" },
  { id: "FRAMEWORK-LGOV-001", label: "LGOV", type: "framework", href: "/library/frameworks/leadership-governance-portal" },
  { id: "leadership-governance", label: "Leadership Governance", type: "system", href: "/library/leadership" },
  { id: "CONSTITUTION-ARTICLE-VI", label: "Article VI", type: "framework", href: "/library/constitution/article-vi" },
  { id: "FRAMEWORK-CDW-001", label: "CDW", type: "framework", href: "/library/frameworks/constitutional-decision-workspace" },
  { id: "decision-workspace", label: "Decision Workspace", type: "system", href: "/library/decision-workspace" },
  { id: "CONSTITUTION-ARTICLE-VII", label: "Article VII", type: "framework", href: "/library/constitution/article-vii" },
  { id: "FRAMEWORK-IAR-001", label: "IAR", type: "framework", href: "/library/frameworks/institutional-asset-registry" },
  { id: "institutional-asset-registry", label: "Asset Registry", type: "system", href: "/library/institutional-assets" },
  { id: "CONSTITUTION-ARTICLE-VIII", label: "Article VIII", type: "framework", href: "/library/constitution/article-viii" },
  { id: "FRAMEWORK-OASP-001", label: "OASP", type: "framework", href: "/library/frameworks/ownership-stewardship-portal" },
  { id: "ownership-stewardship", label: "Ownership & Stewardship", type: "system", href: "/library/ownership-stewardship" },
  { id: "CONSTITUTION-ARTICLE-IX", label: "Article IX", type: "framework", href: "/library/constitution/article-ix" },
  { id: "FRAMEWORK-IEP-001", label: "IEP", type: "framework", href: "/library/frameworks/institutional-ecosystem-portal" },
  { id: "ecosystem-architecture", label: "Ecosystem Architecture", type: "system", href: "/library/ecosystem-architecture" },
  { id: "CONSTITUTION-ARTICLE-X", label: "Article X", type: "framework", href: "/library/constitution/article-x" },
  { id: "FRAMEWORK-ILR-001", label: "ILR", type: "framework", href: "/library/frameworks/institution-lifecycle-registry" },
  { id: "institution-lifecycle", label: "Institution Lifecycle", type: "system", href: "/library/institution-lifecycle" },
  { id: "FRAMEWORK-INP-001", label: "INP", type: "framework", href: "/library/frameworks/innovation-portal" },
  { id: "innovation-portal", label: "Innovation Portal", type: "system", href: "/library/innovation-portal" },
  { id: "venture-studio", label: "Venture Studio", type: "system", href: "/library/innovation-portal" },
  { id: "constitution-schedules", label: "Constitutional Schedules", type: "volume", href: "/library/constitution/schedules" },
  { id: "CONSTITUTION-SCHEDULE-H", label: "Schedule H", type: "framework", href: "/library/constitution/schedules#schedule-h" },
  { id: "CONSTITUTION-ARTICLE-XI", label: "Article XI", type: "framework", href: "/library/constitution/article-xi" },
  { id: "FRAMEWORK-IEC-001", label: "IEC", type: "framework", href: "/library/frameworks/integrity-ethics-centre" },
  { id: "integrity-ethics", label: "Integrity & Ethics", type: "system", href: "/library/integrity-ethics" },
  { id: "CONSTITUTION-ARTICLE-XII", label: "Article XII", type: "framework", href: "/library/constitution/article-xii" },
  { id: "FRAMEWORK-CTC-001", label: "CTC", type: "framework", href: "/library/frameworks/constitutional-trust-centre" },
  { id: "constitutional-trust", label: "Constitutional Trust", type: "system", href: "/library/constitutional-trust" },
  { id: "CONSTITUTION-ARTICLE-XIII", label: "Article XIII", type: "framework", href: "/library/constitution/article-xiii" },
  { id: "FRAMEWORK-SLP-001", label: "SLP", type: "framework", href: "/library/frameworks/stankings-library-portal" },
  { id: "stankings-library", label: "Stankings Library Portal", type: "system", href: "/library/stankings-library" },
  { id: "CONSTITUTION-ARTICLE-XIV", label: "Article XIV", type: "framework", href: "/library/constitution/article-xiv" },
  { id: "FRAMEWORK-CHD-001", label: "CHD", type: "framework", href: "/library/frameworks/constitutional-health-dashboard" },
  { id: "constitutional-health", label: "Constitutional Health", type: "system", href: "/library/constitutional-health" },
  { id: "CONSTITUTION-ARTICLE-XV", label: "Article XV", type: "framework", href: "/library/constitution/article-xv" },
  { id: "FRAMEWORK-CCR-001", label: "CCR", type: "framework", href: "/library/frameworks/constitution-centre" },
  { id: "constitution-centre", label: "Constitution Centre", type: "system", href: "/library/constitution-centre" },
  { id: "CONSTITUTION-ARTICLE-XVI", label: "Article XVI", type: "framework", href: "/library/constitution/article-xvi" },
  { id: "FRAMEWORK-CPP-001", label: "CPP", type: "framework", href: "/library/frameworks/custodian-programme-portal" },
  { id: "custodian-programme-portal", label: "Custodian Programme", type: "system", href: "/library/custodian-programme" },
  { id: "CONSTITUTION-ARTICLE-XVII", label: "Article XVII", type: "framework", href: "/library/constitution/article-xvii" },
  { id: "FRAMEWORK-CCY-001", label: "CCY", type: "framework", href: "/library/frameworks/constitutional-ceremony-portal" },
  { id: "constitutional-ceremony-portal", label: "Constitutional Ceremony", type: "system", href: "/library/constitutional-ceremony" },
  { id: "founders-charge", label: "Founder's Charge", type: "framework", href: "/library/constitution/founders-charge" },
  { id: "CONVENTION-VOL-I-001", label: "Convention", type: "framework", href: "/library/constitutional-convention" },
  { id: "constitutional-convention", label: "Convention Portal", type: "system", href: "/library/constitutional-convention" },
  { id: "VOLUME-II-GOVERNANCE-CODE", label: "Volume II", type: "volume", href: "/library/governance-code" },
  { id: "FRAMEWORK-GC-001", label: "GC Portal", type: "framework", href: "/library/frameworks/governance-code-portal" },
  { id: "BOOK-I-GOVERNANCE-BODIES", label: "Book I", type: "framework", href: "/library/governance-code/book-i" },
  { id: "governance-code-portal", label: "Governance Code", type: "system", href: "/library/governance-code" },
  { id: "FRAMEWORK-LIB-SESS-001", label: "Session Records", type: "framework", href: "/library/sessions" },
  { id: "FRAMEWORK-EDW-001", label: "Editorial Workflow", type: "framework", href: "/library/editorial-standards/editorial-workflow" },
  { id: "editorial-standards", label: "Editorial Standards", type: "system", href: "/library/editorial-standards" },
  { id: "LIB-2026-06-27-003", label: "Session 003", type: "framework", href: "/library/sessions/LIB-2026-06-27-003" },
  { id: "FRAMEWORK-SLPS-001", label: "SLPS-001", type: "framework", href: "/library/editorial-standards/publishing-standard" },
  { id: "FRAMEWORK-LPS-001", label: "LPS (Legacy)", type: "framework", href: "/library/editorial-standards/publishing-standard" },
  { id: "PUB-ENGINE-001", label: "Publication Generator", type: "system", href: "/library/editorial-standards/publishing-standard/generator" },
  { id: "FRAMEWORK-SLPS-CORE-001", label: "SLPS-CORE", type: "framework", href: "/library/editorial-standards/publishing-system" },
  { id: "LIB-2026-06-27-008", label: "Session 008", type: "framework", href: "/library/sessions/LIB-2026-06-27-008" },
  { id: "slps-core", label: "Publishing System", type: "system", href: "/library/editorial-standards/publishing-system" },
  { id: "BOOK-I-FOUNDATIONAL-CHARTER", label: "Foundational Charter", type: "framework", href: "/library/governance-code/book-i/foundational-charter" },
  { id: "BOOK-I-CHARTER", label: "Book Charter (Legacy)", type: "framework", href: "/library/governance-code/book-i/foundational-charter" },
  { id: "FRAMEWORK-FC-001", label: "FC-001", type: "framework", href: "/library/editorial-standards/foundational-charter" },
  { id: "FRAMEWORK-CEF-001", label: "CEF-001", type: "framework", href: "/library/editorial-standards/chapter-education" },
  { id: "BOOK-I-CH-01-ARCHITECTURE", label: "Chapter 1 Architecture", type: "framework", href: "/library/governance-code/book-i/chapters/book-i-ch-01/architecture" },
  { id: "LIB-2026-07-03-013", label: "Session 013", type: "framework", href: "/library/sessions/LIB-2026-07-03-013" },
  { id: "FOUNDER-INSIGHT-001", label: "Sustainable Stewardship", type: "framework", href: "/library/founder-insights/sustainable-stewardship" },
  { id: "LIB-2026-06-27-012", label: "Session 012", type: "framework", href: "/library/sessions/LIB-2026-06-27-012" },
  { id: "LIB-2026-06-27-011", label: "Session 011", type: "framework", href: "/library/sessions/LIB-2026-06-27-011" },
  { id: "LIB-2026-06-27-009", label: "Session 009", type: "framework", href: "/library/sessions/LIB-2026-06-27-009" },
  { id: "LIB-2026-06-27-007", label: "Session 007", type: "framework", href: "/library/sessions/LIB-2026-06-27-007" },
  { id: "LIB-2026-06-27-006", label: "Session 006", type: "framework", href: "/library/sessions/LIB-2026-06-27-006" },
  { id: "BOOK-I-ARCHITECTURE", label: "Book I Architecture", type: "framework", href: "/library/governance-code/book-i" },
  { id: "LIB-2026-06-27-001", label: "Session 001", type: "framework", href: "/library/sessions/LIB-2026-06-27-001" },
  { id: "LIB-2026-06-27-002", label: "Session 002", type: "framework", href: "/library/sessions/LIB-2026-06-27-002" },
  { id: "library-sessions", label: "Library Sessions", type: "system", href: "/library/sessions" },
  { id: "engineering", label: "Engineering Standards", type: "volume", href: "/library/volumes/engineering-standards" },
  { id: "bayright", label: "BayRight", type: "company", href: "/companies/bayright" },
  { id: "yike", label: "Yike", type: "company", href: "/companies/yike" },
  { id: "passport", label: "Yike Passport", type: "system" },
  { id: "verification", label: "Verification", type: "capability" },
  { id: "escrow", label: "Escrow", type: "capability" },
  { id: "ai", label: "Institutional AI", type: "system" },
  { id: "support", label: "Customer Support", type: "capability" },
  { id: "FRAMEWORK-TIA-001", label: "TIA", type: "framework", href: "/library/frameworks/trust-impact-assessment" },
  { id: "FRAMEWORK-PAF-001", label: "PAF", type: "framework", href: "/library/frameworks/purpose-assessment" },
  { id: "stanhan", label: "Stanhan", type: "company", href: "/library/ecosystem/stanhan" },
  { id: "stankings-auto-hub", label: "Auto Hub", type: "company", href: "/library/ecosystem/stankings-auto-hub" },
  { id: "stankings-logistics", label: "Logistics", type: "company", href: "/library/ecosystem/stankings-logistics" },
  { id: "hannahkings-gadgets", label: "Hannahkings Gadgets", type: "company", href: "/library/ecosystem/hannahkings-gadgets" },
  { id: "FRAMEWORK-LSF-001", label: "LSF", type: "framework", href: "/library/frameworks/leadership-stewardship" },
  { id: "FRAMEWORK-EIA-001", label: "EIA", type: "framework", href: "/library/frameworks/ecosystem-impact-assessment" },
  { id: "FRAMEWORK-GRF-001", label: "GRF", type: "framework", href: "/library/frameworks/generational-review" },
  { id: "FRAMEWORK-IDR-001", label: "IDR", type: "framework", href: "/library/frameworks/institutional-decision-record" },
  { id: "FRAMEWORK-EXF-001", label: "EXF", type: "framework", href: "/library/frameworks/excellence" },
  { id: "FRAMEWORK-LLR-001", label: "LLR", type: "framework", href: "/library/frameworks/lessons-learned" },
  { id: "FRAMEWORK-HIR-001", label: "HIR", type: "framework", href: "/library/frameworks/human-impact-review" },
  { id: "FRAMEWORK-SR-001", label: "SR", type: "framework", href: "/library/frameworks/simplicity-review" },
  { id: "FRAMEWORK-PLAT-001", label: "PLAT", type: "framework", href: "/library/frameworks/platform-assessment" },
  { id: "FRAMEWORK-IGF-001", label: "IGF", type: "framework", href: "/library/frameworks/innovation-governance" },
  { id: "FRAMEWORK-IIAF-001", label: "IIAF", type: "framework", href: "/library/frameworks/incident-accountability" },
  { id: "FRAMEWORK-ISA-001", label: "ISA", type: "framework", href: "/library/frameworks/institutional-strength-assessment" },
  { id: "FRAMEWORK-URF-001", label: "URF", type: "framework", href: "/library/frameworks/uncertainty-reduction" },
  { id: "FRAMEWORK-PAR-001", label: "PAR", type: "framework", href: "/library/frameworks/principles-alignment-review" },
  { id: "FRAMEWORK-IIR-001", label: "IIR", type: "framework", href: "/library/improvements" },
  { id: "FRAMEWORK-ASR-001", label: "ASR", type: "framework", href: "/library/frameworks/annual-stewardship-review" },
  { id: "FRAMEWORK-IDI-001", label: "IDI", type: "framework", href: "/library/decision-intelligence" },
  { id: "FRAMEWORK-IKG-001", label: "IKG", type: "framework", href: "/library/knowledge-graph" },
  { id: "FRAMEWORK-LEGACY-001", label: "LEGACY", type: "framework", href: "/library/legacy" },
  { id: "FRAMEWORK-KCP-001", label: "KCP", type: "framework", href: "/library/knowledge-challenges" },
  { id: "FRAMEWORK-ILD-001", label: "ILD", type: "framework", href: "/library/industry-leadership" },
  { id: "FRAMEWORK-CMD-001", label: "CMD", type: "framework", href: "/library/canon-maturity" },
  { id: "platform-registry", label: "Platform Registry", type: "volume", href: "/library/platforms" },
  { id: "commitment-registry", label: "Commitment Registry", type: "volume", href: "/library/commitments" },
  { id: "incident-center", label: "Incident Center", type: "volume", href: "/library/incidents" },
  { id: "improvement-registry", label: "Improvement Register", type: "volume", href: "/library/improvements" },
  { id: "decision-intelligence", label: "Decision Intelligence", type: "volume", href: "/library/decision-intelligence" },
  { id: "knowledge-graph", label: "Knowledge Graph", type: "volume", href: "/library/knowledge-graph" },
  { id: "legacy-dashboard", label: "Legacy Dashboard", type: "volume", href: "/library/legacy" },
  { id: "knowledge-challenges", label: "Knowledge Challenges", type: "volume", href: "/library/knowledge-challenges" },
  { id: "industry-leadership", label: "Industry Leadership", type: "volume", href: "/library/industry-leadership" },
  { id: "canon-maturity", label: "Canon Maturity", type: "volume", href: "/library/canon-maturity" },
  { id: "ls-001", label: "LS-001", type: "volume", href: "/library/standards/ls-001" },
  { id: "canon-dashboard", label: "Canon Dashboard", type: "volume", href: "/library/canon-dashboard" },
  { id: "excellence-standards", label: "Excellence Standards", type: "volume", href: "/library/excellence" },
  { id: "llr-registry", label: "Lessons Learned", type: "volume", href: "/library/lessons" },
  { id: "idr-registry", label: "Decision Records", type: "volume", href: "/library/decisions" },
];

export const INSTITUTIONAL_GRAPH_EDGES: GraphEdge[] = [
  { from: "trust", to: "CANON-002", relationship: "defines" },
  { from: "CANON-001", to: "CANON-002", relationship: "supports" },
  { from: "CANON-002", to: "CANON-003", relationship: "supports" },
  { from: "CANON-002", to: "FRAMEWORK-TIA-001", relationship: "implements" },
  { from: "CANON-003", to: "FRAMEWORK-PAF-001", relationship: "implements" },
  { from: "CANON-003", to: "CANON-004", relationship: "supports" },
  { from: "CANON-004", to: "CANON-005", relationship: "supports" },
  { from: "CANON-004", to: "FRAMEWORK-LSF-001", relationship: "implements" },
  { from: "CANON-004", to: "custodian-programme", relationship: "supports" },
  { from: "CANON-005", to: "CANON-006", relationship: "supports" },
  { from: "CANON-005", to: "FRAMEWORK-EIA-001", relationship: "implements" },
  { from: "CANON-005", to: "ecosystem-map", relationship: "supports" },
  { from: "CANON-006", to: "CANON-007", relationship: "supports" },
  { from: "CANON-006", to: "FRAMEWORK-GRF-001", relationship: "implements" },
  { from: "CANON-006", to: "custodian-programme", relationship: "supports" },
  { from: "CANON-007", to: "CANON-008", relationship: "supports" },
  { from: "CANON-007", to: "FRAMEWORK-IDR-001", relationship: "implements" },
  { from: "CANON-007", to: "idr-registry", relationship: "supports" },
  { from: "CANON-008", to: "FRAMEWORK-EXF-001", relationship: "implements" },
  { from: "CANON-008", to: "excellence-standards", relationship: "supports" },
  { from: "CANON-008", to: "yike", relationship: "applied_in" },
  { from: "CANON-008", to: "stankings-auto-hub", relationship: "applied_in" },
  { from: "CANON-008", to: "CANON-009", relationship: "supports" },
  { from: "CANON-009", to: "FRAMEWORK-LLR-001", relationship: "implements" },
  { from: "CANON-009", to: "llr-registry", relationship: "supports" },
  { from: "CANON-009", to: "engineering", relationship: "applied_in" },
  { from: "CANON-009", to: "CANON-010", relationship: "supports" },
  { from: "CANON-010", to: "FRAMEWORK-HIR-001", relationship: "implements" },
  { from: "CANON-010", to: "yike", relationship: "applied_in" },
  { from: "CANON-010", to: "bayright", relationship: "applied_in" },
  { from: "CANON-010", to: "CANON-011", relationship: "supports" },
  { from: "CANON-011", to: "FRAMEWORK-SR-001", relationship: "implements" },
  { from: "CANON-011", to: "engineering", relationship: "applied_in" },
  { from: "CANON-011", to: "yike", relationship: "applied_in" },
  { from: "CANON-011", to: "CANON-012", relationship: "supports" },
  { from: "CANON-012", to: "FRAMEWORK-PLAT-001", relationship: "implements" },
  { from: "CANON-012", to: "platform-registry", relationship: "supports" },
  { from: "CANON-012", to: "ecosystem-map", relationship: "references" },
  { from: "CANON-012", to: "engineering", relationship: "applied_in" },
  { from: "CANON-012", to: "bayright", relationship: "applied_in" },
  { from: "CANON-012", to: "stankings-logistics", relationship: "applied_in" },
  { from: "CANON-005", to: "CANON-012", relationship: "supports" },
  { from: "CANON-012", to: "CANON-013", relationship: "supports" },
  { from: "CANON-013", to: "FRAMEWORK-IGF-001", relationship: "implements" },
  { from: "CANON-013", to: "ai", relationship: "applied_in" },
  { from: "CANON-013", to: "engineering", relationship: "applied_in" },
  { from: "CANON-003", to: "CANON-013", relationship: "supports" },
  { from: "CANON-009", to: "CANON-013", relationship: "supports" },
  { from: "FRAMEWORK-IGF-001", to: "FRAMEWORK-PAF-001", relationship: "references" },
  { from: "FRAMEWORK-IGF-001", to: "FRAMEWORK-TIA-001", relationship: "references" },
  { from: "FRAMEWORK-IGF-001", to: "FRAMEWORK-EIA-001", relationship: "references" },
  { from: "FRAMEWORK-IGF-001", to: "FRAMEWORK-GRF-001", relationship: "references" },
  { from: "FRAMEWORK-IGF-001", to: "FRAMEWORK-SR-001", relationship: "references" },
  { from: "FRAMEWORK-IGF-001", to: "FRAMEWORK-PLAT-001", relationship: "references" },
  { from: "CANON-013", to: "CANON-014", relationship: "supports" },
  { from: "CANON-014", to: "commitment-registry", relationship: "supports" },
  { from: "CANON-014", to: "yike", relationship: "applied_in" },
  { from: "CANON-014", to: "bayright", relationship: "applied_in" },
  { from: "CANON-014", to: "bamsignal", relationship: "applied_in" },
  { from: "CANON-002", to: "CANON-014", relationship: "supports" },
  { from: "CANON-007", to: "CANON-014", relationship: "supports" },
  { from: "CANON-014", to: "CANON-015", relationship: "supports" },
  { from: "CANON-015", to: "FRAMEWORK-IIAF-001", relationship: "implements" },
  { from: "CANON-015", to: "incident-center", relationship: "supports" },
  { from: "CANON-015", to: "canon-dashboard", relationship: "supports" },
  { from: "CANON-015", to: "llr-registry", relationship: "supports" },
  { from: "CANON-009", to: "CANON-015", relationship: "supports" },
  { from: "CANON-002", to: "CANON-015", relationship: "supports" },
  { from: "FRAMEWORK-IIAF-001", to: "FRAMEWORK-LLR-001", relationship: "references" },
  { from: "FRAMEWORK-IIAF-001", to: "FRAMEWORK-IDR-001", relationship: "references" },
  { from: "CANON-015", to: "CANON-016", relationship: "supports" },
  { from: "CANON-016", to: "FRAMEWORK-ISA-001", relationship: "implements" },
  { from: "CANON-016", to: "ecosystem-map", relationship: "references" },
  { from: "CANON-016", to: "canon-dashboard", relationship: "supports" },
  { from: "CANON-003", to: "CANON-016", relationship: "supports" },
  { from: "CANON-005", to: "CANON-016", relationship: "supports" },
  { from: "CANON-006", to: "CANON-016", relationship: "supports" },
  { from: "FRAMEWORK-ISA-001", to: "FRAMEWORK-PAF-001", relationship: "references" },
  { from: "FRAMEWORK-ISA-001", to: "FRAMEWORK-EIA-001", relationship: "references" },
  { from: "FRAMEWORK-ISA-001", to: "FRAMEWORK-GRF-001", relationship: "references" },
  { from: "CANON-016", to: "yike", relationship: "applied_in" },
  { from: "CANON-016", to: "stanhan", relationship: "applied_in" },
  { from: "CANON-016", to: "CANON-017", relationship: "supports" },
  { from: "CANON-017", to: "FRAMEWORK-URF-001", relationship: "implements" },
  { from: "CANON-017", to: "ecosystem-map", relationship: "supports" },
  { from: "CANON-017", to: "yike", relationship: "applied_in" },
  { from: "CANON-017", to: "bayright", relationship: "applied_in" },
  { from: "CANON-017", to: "bamsignal", relationship: "applied_in" },
  { from: "CANON-001", to: "CANON-017", relationship: "supports" },
  { from: "CANON-002", to: "CANON-017", relationship: "supports" },
  { from: "CANON-003", to: "CANON-017", relationship: "supports" },
  { from: "FRAMEWORK-URF-001", to: "FRAMEWORK-PAF-001", relationship: "references" },
  { from: "FRAMEWORK-URF-001", to: "FRAMEWORK-TIA-001", relationship: "references" },
  { from: "CANON-017", to: "CANON-018", relationship: "supports" },
  { from: "CANON-018", to: "FRAMEWORK-PAR-001", relationship: "implements" },
  { from: "CANON-018", to: "constitution", relationship: "references" },
  { from: "CANON-001", to: "CANON-018", relationship: "supports" },
  { from: "CANON-002", to: "CANON-018", relationship: "supports" },
  { from: "CANON-003", to: "CANON-018", relationship: "supports" },
  { from: "CANON-014", to: "CANON-018", relationship: "supports" },
  { from: "FRAMEWORK-PAR-001", to: "FRAMEWORK-PAF-001", relationship: "references" },
  { from: "FRAMEWORK-PAR-001", to: "FRAMEWORK-TIA-001", relationship: "references" },
  { from: "FRAMEWORK-PAR-001", to: "FRAMEWORK-EIA-001", relationship: "references" },
  { from: "FRAMEWORK-PAR-001", to: "FRAMEWORK-ISA-001", relationship: "references" },
  { from: "FRAMEWORK-PAR-001", to: "FRAMEWORK-URF-001", relationship: "references" },
  { from: "CANON-018", to: "CANON-019", relationship: "supports" },
  { from: "CANON-019", to: "FRAMEWORK-IIR-001", relationship: "implements" },
  { from: "CANON-019", to: "FRAMEWORK-ASR-001", relationship: "implements" },
  { from: "CANON-019", to: "improvement-registry", relationship: "supports" },
  { from: "CANON-004", to: "CANON-019", relationship: "supports" },
  { from: "CANON-006", to: "CANON-019", relationship: "supports" },
  { from: "CANON-009", to: "CANON-019", relationship: "supports" },
  { from: "CANON-016", to: "CANON-019", relationship: "supports" },
  { from: "FRAMEWORK-IIR-001", to: "FRAMEWORK-LLR-001", relationship: "references" },
  { from: "FRAMEWORK-ASR-001", to: "FRAMEWORK-IIR-001", relationship: "references" },
  { from: "FRAMEWORK-ASR-001", to: "CANON-019", relationship: "depends_on" },
  { from: "CANON-019", to: "CANON-020", relationship: "supports" },
  { from: "CANON-020", to: "FRAMEWORK-IDI-001", relationship: "implements" },
  { from: "CANON-020", to: "decision-intelligence", relationship: "supports" },
  { from: "CANON-007", to: "CANON-020", relationship: "supports" },
  { from: "CANON-009", to: "CANON-020", relationship: "supports" },
  { from: "CANON-002", to: "CANON-020", relationship: "supports" },
  { from: "FRAMEWORK-IDI-001", to: "FRAMEWORK-IDR-001", relationship: "references" },
  { from: "FRAMEWORK-IDI-001", to: "FRAMEWORK-PAR-001", relationship: "references" },
  { from: "FRAMEWORK-IDI-001", to: "FRAMEWORK-URF-001", relationship: "references" },
  { from: "FRAMEWORK-IDI-001", to: "CANON-020", relationship: "depends_on" },
  { from: "CANON-020", to: "CANON-021", relationship: "supports" },
  { from: "CANON-021", to: "FRAMEWORK-IKG-001", relationship: "implements" },
  { from: "CANON-021", to: "knowledge-graph", relationship: "supports" },
  { from: "CANON-021", to: "ls-001", relationship: "references" },
  { from: "CANON-009", to: "CANON-021", relationship: "supports" },
  { from: "CANON-006", to: "CANON-021", relationship: "supports" },
  { from: "CANON-019", to: "CANON-021", relationship: "supports" },
  { from: "FRAMEWORK-IKG-001", to: "FRAMEWORK-IDR-001", relationship: "references" },
  { from: "FRAMEWORK-IKG-001", to: "FRAMEWORK-LLR-001", relationship: "references" },
  { from: "FRAMEWORK-IKG-001", to: "FRAMEWORK-IDI-001", relationship: "references" },
  { from: "FRAMEWORK-IKG-001", to: "CANON-021", relationship: "depends_on" },
  { from: "ls-001", to: "CANON-021", relationship: "supports" },
  { from: "llr-registry", to: "CANON-021", relationship: "supports" },
  { from: "idr-registry", to: "CANON-021", relationship: "supports" },
  { from: "CANON-021", to: "CANON-022", relationship: "supports" },
  { from: "CANON-001", to: "CANON-022", relationship: "supports" },
  { from: "CANON-003", to: "CANON-022", relationship: "supports" },
  { from: "CANON-006", to: "CANON-022", relationship: "supports" },
  { from: "CANON-019", to: "CANON-022", relationship: "supports" },
  { from: "CANON-022", to: "FRAMEWORK-LEGACY-001", relationship: "implements" },
  { from: "CANON-022", to: "legacy-dashboard", relationship: "supports" },
  { from: "FRAMEWORK-LEGACY-001", to: "CANON-022", relationship: "depends_on" },
  { from: "FRAMEWORK-LEGACY-001", to: "FRAMEWORK-ASR-001", relationship: "references" },
  { from: "FRAMEWORK-LEGACY-001", to: "FRAMEWORK-IIR-001", relationship: "references" },
  { from: "FRAMEWORK-LEGACY-001", to: "CANON-019", relationship: "references" },
  { from: "CANON-022", to: "canon-dashboard", relationship: "supports" },
  { from: "stankings-foundation", to: "CANON-022", relationship: "supports" },
  { from: "CANON-022", to: "CANON-023", relationship: "supports" },
  { from: "CANON-007", to: "CANON-023", relationship: "supports" },
  { from: "CANON-009", to: "CANON-023", relationship: "supports" },
  { from: "CANON-020", to: "CANON-023", relationship: "supports" },
  { from: "CANON-023", to: "FRAMEWORK-KCP-001", relationship: "implements" },
  { from: "CANON-023", to: "knowledge-challenges", relationship: "supports" },
  { from: "FRAMEWORK-KCP-001", to: "CANON-023", relationship: "depends_on" },
  { from: "FRAMEWORK-KCP-001", to: "FRAMEWORK-LLR-001", relationship: "references" },
  { from: "FRAMEWORK-KCP-001", to: "FRAMEWORK-IDI-001", relationship: "references" },
  { from: "FRAMEWORK-KCP-001", to: "CANON-009", relationship: "references" },
  { from: "CANON-023", to: "canon-dashboard", relationship: "supports" },
  { from: "llr-registry", to: "CANON-023", relationship: "supports" },
  { from: "CANON-023", to: "CANON-024", relationship: "supports" },
  { from: "CANON-008", to: "CANON-024", relationship: "supports" },
  { from: "CANON-017", to: "CANON-024", relationship: "supports" },
  { from: "CANON-022", to: "CANON-024", relationship: "supports" },
  { from: "CANON-024", to: "FRAMEWORK-ILD-001", relationship: "implements" },
  { from: "CANON-024", to: "industry-leadership", relationship: "supports" },
  { from: "FRAMEWORK-ILD-001", to: "CANON-024", relationship: "depends_on" },
  { from: "FRAMEWORK-ILD-001", to: "FRAMEWORK-LEGACY-001", relationship: "references" },
  { from: "FRAMEWORK-ILD-001", to: "FRAMEWORK-EXF-001", relationship: "references" },
  { from: "CANON-024", to: "canon-dashboard", relationship: "supports" },
  { from: "CANON-024", to: "legacy-dashboard", relationship: "references" },
  { from: "excellence-standards", to: "CANON-024", relationship: "supports" },
  { from: "CANON-024", to: "CANON-025", relationship: "supports" },
  { from: "CANON-001", to: "CANON-025", relationship: "supports" },
  { from: "CANON-004", to: "CANON-025", relationship: "supports" },
  { from: "CANON-006", to: "CANON-025", relationship: "supports" },
  { from: "CANON-019", to: "CANON-025", relationship: "supports" },
  { from: "CANON-022", to: "CANON-025", relationship: "supports" },
  { from: "CANON-025", to: "FRAMEWORK-CMD-001", relationship: "implements" },
  { from: "CANON-025", to: "canon-maturity", relationship: "supports" },
  { from: "FRAMEWORK-CMD-001", to: "CANON-025", relationship: "depends_on" },
  { from: "FRAMEWORK-CMD-001", to: "FRAMEWORK-IKG-001", relationship: "references" },
  { from: "CANON-025", to: "constitution", relationship: "supports" },
  { from: "constitution", to: "CANON-001", relationship: "implements" },
  { from: "constitution", to: "CANON-002", relationship: "implements" },
  { from: "constitution", to: "CANON-003", relationship: "implements" },
  { from: "constitution", to: "CANON-004", relationship: "implements" },
  { from: "constitution", to: "CANON-005", relationship: "implements" },
  { from: "constitution", to: "CANON-006", relationship: "implements" },
  { from: "constitution", to: "CANON-007", relationship: "implements" },
  { from: "constitution", to: "CANON-025", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-I", to: "constitution", relationship: "depends_on" },
  { from: "constitution", to: "CONSTITUTION-ARTICLE-I", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-I", to: "CANON-001", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-I", to: "CANON-003", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-I", to: "CANON-005", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-I", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-I", to: "FRAMEWORK-IIS-001", relationship: "supports" },
  { from: "FRAMEWORK-IIS-001", to: "CONSTITUTION-ARTICLE-I", relationship: "depends_on" },
  { from: "FRAMEWORK-IIS-001", to: "CANON-005", relationship: "depends_on" },
  { from: "FRAMEWORK-IIS-001", to: "institutional-identity", relationship: "supports" },
  { from: "FRAMEWORK-IIS-001", to: "ecosystem-map", relationship: "references" },
  { from: "CANON-005", to: "CONSTITUTION-ARTICLE-I", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-II", to: "constitution", relationship: "depends_on" },
  { from: "constitution", to: "CONSTITUTION-ARTICLE-II", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-II", to: "CONSTITUTION-ARTICLE-I", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-II", to: "CANON-001", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-II", to: "CANON-003", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-II", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-II", to: "CANON-011", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-II", to: "CANON-017", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-II", to: "CANON-018", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-II", to: "CANON-022", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-II", to: "FRAMEWORK-CAE-001", relationship: "supports" },
  { from: "FRAMEWORK-CAE-001", to: "CONSTITUTION-ARTICLE-II", relationship: "depends_on" },
  { from: "FRAMEWORK-CAE-001", to: "CONSTITUTION-ARTICLE-I", relationship: "depends_on" },
  { from: "FRAMEWORK-CAE-001", to: "FRAMEWORK-PAF-001", relationship: "references" },
  { from: "FRAMEWORK-CAE-001", to: "FRAMEWORK-TIA-001", relationship: "references" },
  { from: "FRAMEWORK-CAE-001", to: "FRAMEWORK-EIA-001", relationship: "references" },
  { from: "FRAMEWORK-CAE-001", to: "constitutional-alignment", relationship: "supports" },
  { from: "CANON-003", to: "CONSTITUTION-ARTICLE-II", relationship: "supports" },
  { from: "CANON-018", to: "CONSTITUTION-ARTICLE-II", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-III", to: "constitution", relationship: "depends_on" },
  { from: "constitution", to: "CONSTITUTION-ARTICLE-III", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-III", to: "CONSTITUTION-ARTICLE-II", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-III", to: "CANON-004", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-III", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-III", to: "CANON-009", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-III", to: "CANON-019", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-III", to: "CANON-021", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-III", to: "CANON-025", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-III", to: "FRAMEWORK-STEWARDSHIP-PORTAL-001", relationship: "supports" },
  { from: "FRAMEWORK-STEWARDSHIP-PORTAL-001", to: "CONSTITUTION-ARTICLE-III", relationship: "depends_on" },
  { from: "FRAMEWORK-STEWARDSHIP-PORTAL-001", to: "FRAMEWORK-LSF-001", relationship: "references" },
  { from: "FRAMEWORK-STEWARDSHIP-PORTAL-001", to: "FRAMEWORK-ASR-001", relationship: "references" },
  { from: "FRAMEWORK-STEWARDSHIP-PORTAL-001", to: "stewardship-portal", relationship: "supports" },
  { from: "FRAMEWORK-STEWARDSHIP-PORTAL-001", to: "custodian-programme", relationship: "references" },
  { from: "CANON-004", to: "CONSTITUTION-ARTICLE-III", relationship: "supports" },
  { from: "CANON-006", to: "CONSTITUTION-ARTICLE-III", relationship: "supports" },
  { from: "constitution", to: "CONSTITUTION-ARTICLE-IV", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-IV", to: "constitution", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-IV", to: "CONSTITUTION-ARTICLE-III", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-IV", to: "CANON-004", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IV", to: "CANON-007", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IV", to: "CANON-015", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IV", to: "CANON-016", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IV", to: "CANON-020", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IV", to: "FRAMEWORK-CGOV-001", relationship: "supports" },
  { from: "FRAMEWORK-CGOV-001", to: "CONSTITUTION-ARTICLE-IV", relationship: "depends_on" },
  { from: "FRAMEWORK-CGOV-001", to: "FRAMEWORK-IDR-001", relationship: "references" },
  { from: "FRAMEWORK-CGOV-001", to: "FRAMEWORK-LSF-001", relationship: "references" },
  { from: "FRAMEWORK-CGOV-001", to: "constitutional-governance", relationship: "supports" },
  { from: "FRAMEWORK-CGOV-001", to: "idr-registry", relationship: "references" },
  { from: "CANON-004", to: "CONSTITUTION-ARTICLE-IV", relationship: "supports" },
  { from: "CANON-007", to: "CONSTITUTION-ARTICLE-IV", relationship: "supports" },
  { from: "CANON-015", to: "CONSTITUTION-ARTICLE-IV", relationship: "supports" },
  { from: "CANON-016", to: "CONSTITUTION-ARTICLE-IV", relationship: "supports" },
  { from: "CANON-020", to: "CONSTITUTION-ARTICLE-IV", relationship: "supports" },
  { from: "constitution", to: "CONSTITUTION-ARTICLE-V", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-V", to: "constitution", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-V", to: "CONSTITUTION-ARTICLE-IV", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-V", to: "CANON-004", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-V", to: "CANON-007", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-V", to: "CANON-010", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-V", to: "CANON-019", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-V", to: "CANON-020", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-V", to: "CANON-023", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-V", to: "FRAMEWORK-LGOV-001", relationship: "supports" },
  { from: "FRAMEWORK-LGOV-001", to: "CONSTITUTION-ARTICLE-V", relationship: "depends_on" },
  { from: "FRAMEWORK-LGOV-001", to: "FRAMEWORK-LSF-001", relationship: "references" },
  { from: "FRAMEWORK-LGOV-001", to: "FRAMEWORK-STEWARDSHIP-PORTAL-001", relationship: "references" },
  { from: "FRAMEWORK-LGOV-001", to: "FRAMEWORK-ASR-001", relationship: "references" },
  { from: "FRAMEWORK-LGOV-001", to: "leadership-governance", relationship: "supports" },
  { from: "FRAMEWORK-LGOV-001", to: "custodian-programme", relationship: "references" },
  { from: "CANON-004", to: "CONSTITUTION-ARTICLE-V", relationship: "supports" },
  { from: "CANON-007", to: "CONSTITUTION-ARTICLE-V", relationship: "supports" },
  { from: "CANON-010", to: "CONSTITUTION-ARTICLE-V", relationship: "supports" },
  { from: "CANON-019", to: "CONSTITUTION-ARTICLE-V", relationship: "supports" },
  { from: "CANON-023", to: "CONSTITUTION-ARTICLE-V", relationship: "supports" },
  { from: "constitution", to: "CONSTITUTION-ARTICLE-VI", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-VI", to: "constitution", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-VI", to: "CONSTITUTION-ARTICLE-V", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-VI", to: "CANON-002", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VI", to: "CANON-003", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VI", to: "CANON-005", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VI", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VI", to: "CANON-007", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VI", to: "CANON-009", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VI", to: "CANON-010", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VI", to: "CANON-017", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VI", to: "CANON-020", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VI", to: "FRAMEWORK-CDW-001", relationship: "supports" },
  { from: "FRAMEWORK-CDW-001", to: "CONSTITUTION-ARTICLE-VI", relationship: "depends_on" },
  { from: "FRAMEWORK-CDW-001", to: "FRAMEWORK-IDR-001", relationship: "references" },
  { from: "FRAMEWORK-CDW-001", to: "FRAMEWORK-CAE-001", relationship: "references" },
  { from: "FRAMEWORK-CDW-001", to: "FRAMEWORK-PAF-001", relationship: "references" },
  { from: "FRAMEWORK-CDW-001", to: "FRAMEWORK-TIA-001", relationship: "references" },
  { from: "FRAMEWORK-CDW-001", to: "FRAMEWORK-EIA-001", relationship: "references" },
  { from: "FRAMEWORK-CDW-001", to: "FRAMEWORK-GRF-001", relationship: "references" },
  { from: "FRAMEWORK-CDW-001", to: "FRAMEWORK-LLR-001", relationship: "references" },
  { from: "FRAMEWORK-CDW-001", to: "decision-workspace", relationship: "supports" },
  { from: "FRAMEWORK-CDW-001", to: "idr-registry", relationship: "references" },
  { from: "FRAMEWORK-CDW-001", to: "decision-intelligence", relationship: "references" },
  { from: "CANON-002", to: "CONSTITUTION-ARTICLE-VI", relationship: "supports" },
  { from: "CANON-007", to: "CONSTITUTION-ARTICLE-VI", relationship: "supports" },
  { from: "CANON-009", to: "CONSTITUTION-ARTICLE-VI", relationship: "supports" },
  { from: "FRAMEWORK-IDR-001", to: "CONSTITUTION-ARTICLE-VI", relationship: "supports" },
  { from: "constitution", to: "CONSTITUTION-ARTICLE-VII", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-VII", to: "constitution", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-VII", to: "CONSTITUTION-ARTICLE-VI", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-VII", to: "CONSTITUTION-ARTICLE-III", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-VII", to: "CANON-002", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VII", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VII", to: "CANON-007", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VII", to: "CANON-014", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VII", to: "CANON-019", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VII", to: "CANON-021", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VII", to: "CANON-025", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VII", to: "FRAMEWORK-IAR-001", relationship: "supports" },
  { from: "FRAMEWORK-IAR-001", to: "CONSTITUTION-ARTICLE-VII", relationship: "depends_on" },
  { from: "FRAMEWORK-IAR-001", to: "CONSTITUTION-ARTICLE-III", relationship: "references" },
  { from: "FRAMEWORK-IAR-001", to: "FRAMEWORK-TIA-001", relationship: "references" },
  { from: "FRAMEWORK-IAR-001", to: "FRAMEWORK-ASR-001", relationship: "references" },
  { from: "FRAMEWORK-IAR-001", to: "FRAMEWORK-IKG-001", relationship: "references" },
  { from: "FRAMEWORK-IAR-001", to: "institutional-asset-registry", relationship: "supports" },
  { from: "FRAMEWORK-IAR-001", to: "commitment-registry", relationship: "references" },
  { from: "FRAMEWORK-IAR-001", to: "platform-registry", relationship: "references" },
  { from: "CANON-002", to: "CONSTITUTION-ARTICLE-VII", relationship: "supports" },
  { from: "CANON-014", to: "CONSTITUTION-ARTICLE-VII", relationship: "supports" },
  { from: "CANON-021", to: "CONSTITUTION-ARTICLE-VII", relationship: "supports" },
  { from: "constitution", to: "CONSTITUTION-ARTICLE-VIII", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-VIII", to: "constitution", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-VIII", to: "CONSTITUTION-ARTICLE-VII", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-VIII", to: "CONSTITUTION-ARTICLE-IV", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-VIII", to: "CANON-004", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VIII", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VIII", to: "CANON-007", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VIII", to: "CANON-016", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VIII", to: "CANON-025", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-VIII", to: "FRAMEWORK-OASP-001", relationship: "supports" },
  { from: "FRAMEWORK-OASP-001", to: "CONSTITUTION-ARTICLE-VIII", relationship: "depends_on" },
  { from: "FRAMEWORK-OASP-001", to: "FRAMEWORK-CGOV-001", relationship: "references" },
  { from: "FRAMEWORK-OASP-001", to: "FRAMEWORK-IAR-001", relationship: "references" },
  { from: "FRAMEWORK-OASP-001", to: "FRAMEWORK-GRF-001", relationship: "references" },
  { from: "FRAMEWORK-OASP-001", to: "ownership-stewardship", relationship: "supports" },
  { from: "FRAMEWORK-OASP-001", to: "custodian-programme", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-VIII", to: "CONSTITUTION-ARTICLE-IX", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "CONSTITUTION-ARTICLE-VIII", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "CONSTITUTION-ARTICLE-I", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "CONSTITUTION-ARTICLE-II", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "CANON-001", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "CANON-002", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "CANON-003", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "CANON-005", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "CANON-011", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "CANON-012", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "CANON-016", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "FRAMEWORK-IEP-001", relationship: "supports" },
  { from: "FRAMEWORK-IEP-001", to: "CONSTITUTION-ARTICLE-IX", relationship: "depends_on" },
  { from: "FRAMEWORK-IEP-001", to: "FRAMEWORK-IIS-001", relationship: "references" },
  { from: "FRAMEWORK-IEP-001", to: "FRAMEWORK-EIA-001", relationship: "references" },
  { from: "FRAMEWORK-IEP-001", to: "FRAMEWORK-CAE-001", relationship: "references" },
  { from: "FRAMEWORK-IEP-001", to: "ecosystem-architecture", relationship: "supports" },
  { from: "FRAMEWORK-IEP-001", to: "ecosystem-map", relationship: "references" },
  { from: "FRAMEWORK-IEP-001", to: "platform-registry", relationship: "references" },
  { from: "ecosystem-architecture", to: "CONSTITUTION-ARTICLE-IX", relationship: "depends_on" },
  { from: "ecosystem-map", to: "ecosystem-architecture", relationship: "references" },
  { from: "CANON-005", to: "CONSTITUTION-ARTICLE-IX", relationship: "supports" },
  { from: "CANON-005", to: "ecosystem-architecture", relationship: "supports" },
  { from: "CANON-012", to: "CONSTITUTION-ARTICLE-IX", relationship: "supports" },
  { from: "CANON-016", to: "CONSTITUTION-ARTICLE-IX", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-IX", to: "CONSTITUTION-ARTICLE-X", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-X", to: "CONSTITUTION-ARTICLE-IX", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-X", to: "CONSTITUTION-ARTICLE-II", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-X", to: "CONSTITUTION-ARTICLE-V", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-X", to: "CANON-003", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-X", to: "CANON-005", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-X", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-X", to: "CANON-009", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-X", to: "CANON-013", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-X", to: "CANON-018", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-X", to: "CANON-021", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-X", to: "CANON-022", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-X", to: "FRAMEWORK-ILR-001", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-X", to: "FRAMEWORK-INP-001", relationship: "supports" },
  { from: "FRAMEWORK-ILR-001", to: "CONSTITUTION-ARTICLE-X", relationship: "depends_on" },
  { from: "FRAMEWORK-ILR-001", to: "FRAMEWORK-IEP-001", relationship: "references" },
  { from: "FRAMEWORK-ILR-001", to: "FRAMEWORK-IIS-001", relationship: "references" },
  { from: "FRAMEWORK-ILR-001", to: "FRAMEWORK-PAR-001", relationship: "references" },
  { from: "FRAMEWORK-ILR-001", to: "institution-lifecycle", relationship: "supports" },
  { from: "FRAMEWORK-INP-001", to: "CONSTITUTION-ARTICLE-X", relationship: "depends_on" },
  { from: "FRAMEWORK-INP-001", to: "CONSTITUTION-SCHEDULE-H", relationship: "references" },
  { from: "FRAMEWORK-INP-001", to: "FRAMEWORK-ILR-001", relationship: "references" },
  { from: "FRAMEWORK-INP-001", to: "FRAMEWORK-PAF-001", relationship: "references" },
  { from: "FRAMEWORK-INP-001", to: "FRAMEWORK-PAR-001", relationship: "references" },
  { from: "FRAMEWORK-INP-001", to: "FRAMEWORK-IGF-001", relationship: "references" },
  { from: "FRAMEWORK-INP-001", to: "innovation-portal", relationship: "supports" },
  { from: "FRAMEWORK-INP-001", to: "venture-studio", relationship: "supports" },
  { from: "innovation-portal", to: "CONSTITUTION-ARTICLE-X", relationship: "depends_on" },
  { from: "institution-lifecycle", to: "CONSTITUTION-ARTICLE-X", relationship: "depends_on" },
  { from: "institution-lifecycle", to: "innovation-portal", relationship: "references" },
  { from: "ecosystem-architecture", to: "institution-lifecycle", relationship: "references" },
  { from: "CANON-013", to: "CONSTITUTION-ARTICLE-X", relationship: "supports" },
  { from: "CANON-018", to: "CONSTITUTION-ARTICLE-X", relationship: "supports" },
  { from: "CANON-021", to: "CONSTITUTION-ARTICLE-X", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-X", to: "CONSTITUTION-ARTICLE-XI", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-XI", to: "CONSTITUTION-ARTICLE-X", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XI", to: "CONSTITUTION-ARTICLE-V", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XI", to: "CONSTITUTION-ARTICLE-IV", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XI", to: "CANON-002", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XI", to: "CANON-004", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XI", to: "CANON-007", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XI", to: "CANON-010", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XI", to: "CANON-020", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XI", to: "CANON-025", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XI", to: "FRAMEWORK-IEC-001", relationship: "supports" },
  { from: "FRAMEWORK-IEC-001", to: "CONSTITUTION-ARTICLE-XI", relationship: "depends_on" },
  { from: "FRAMEWORK-IEC-001", to: "FRAMEWORK-LGOV-001", relationship: "references" },
  { from: "FRAMEWORK-IEC-001", to: "FRAMEWORK-CGOV-001", relationship: "references" },
  { from: "FRAMEWORK-IEC-001", to: "integrity-ethics", relationship: "supports" },
  { from: "integrity-ethics", to: "CONSTITUTION-ARTICLE-XI", relationship: "depends_on" },
  { from: "CANON-002", to: "CONSTITUTION-ARTICLE-XI", relationship: "supports" },
  { from: "CANON-004", to: "CONSTITUTION-ARTICLE-XI", relationship: "supports" },
  { from: "CANON-007", to: "CONSTITUTION-ARTICLE-XI", relationship: "supports" },
  { from: "CANON-010", to: "CONSTITUTION-ARTICLE-XI", relationship: "supports" },
  { from: "CANON-020", to: "CONSTITUTION-ARTICLE-XI", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XI", to: "CONSTITUTION-ARTICLE-XII", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "CONSTITUTION-ARTICLE-XI", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "CONSTITUTION-ARTICLE-IX", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "CONSTITUTION-ARTICLE-VII", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "CANON-002", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "CANON-007", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "CANON-010", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "CANON-012", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "CANON-013", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "CANON-021", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "FRAMEWORK-CTC-001", relationship: "supports" },
  { from: "FRAMEWORK-CTC-001", to: "CONSTITUTION-ARTICLE-XII", relationship: "depends_on" },
  { from: "FRAMEWORK-CTC-001", to: "FRAMEWORK-PLAT-001", relationship: "references" },
  { from: "FRAMEWORK-CTC-001", to: "FRAMEWORK-TIA-001", relationship: "references" },
  { from: "FRAMEWORK-CTC-001", to: "FRAMEWORK-HIR-001", relationship: "references" },
  { from: "FRAMEWORK-CTC-001", to: "FRAMEWORK-IGF-001", relationship: "references" },
  { from: "FRAMEWORK-CTC-001", to: "FRAMEWORK-IEC-001", relationship: "references" },
  { from: "FRAMEWORK-CTC-001", to: "constitutional-trust", relationship: "supports" },
  { from: "constitutional-trust", to: "CONSTITUTION-ARTICLE-XII", relationship: "depends_on" },
  { from: "constitutional-trust", to: "passport", relationship: "supports" },
  { from: "constitutional-trust", to: "verification", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "passport", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "ai", relationship: "supports" },
  { from: "CANON-002", to: "CONSTITUTION-ARTICLE-XII", relationship: "supports" },
  { from: "CANON-007", to: "CONSTITUTION-ARTICLE-XII", relationship: "supports" },
  { from: "CANON-010", to: "CONSTITUTION-ARTICLE-XII", relationship: "supports" },
  { from: "CANON-012", to: "CONSTITUTION-ARTICLE-XII", relationship: "supports" },
  { from: "CANON-013", to: "CONSTITUTION-ARTICLE-XII", relationship: "supports" },
  { from: "CANON-021", to: "CONSTITUTION-ARTICLE-XII", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XII", to: "CONSTITUTION-ARTICLE-XIII", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-XIII", to: "CONSTITUTION-ARTICLE-XII", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XIII", to: "CONSTITUTION-ARTICLE-VII", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XIII", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIII", to: "CANON-009", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIII", to: "CANON-019", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIII", to: "CANON-020", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIII", to: "CANON-021", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIII", to: "CANON-022", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIII", to: "CANON-023", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIII", to: "FRAMEWORK-SLP-001", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XIII", to: "FRAMEWORK-IKG-001", relationship: "supports" },
  { from: "FRAMEWORK-SLP-001", to: "CONSTITUTION-ARTICLE-XIII", relationship: "depends_on" },
  { from: "FRAMEWORK-SLP-001", to: "FRAMEWORK-IKG-001", relationship: "references" },
  { from: "FRAMEWORK-SLP-001", to: "LS-001", relationship: "references" },
  { from: "FRAMEWORK-SLP-001", to: "LS-002", relationship: "references" },
  { from: "FRAMEWORK-SLP-001", to: "library-engine", relationship: "references" },
  { from: "FRAMEWORK-SLP-001", to: "stankings-library", relationship: "supports" },
  { from: "stankings-library", to: "CONSTITUTION-ARTICLE-XIII", relationship: "depends_on" },
  { from: "stankings-library", to: "knowledge-graph", relationship: "references" },
  { from: "FRAMEWORK-IKG-001", to: "CONSTITUTION-ARTICLE-XIII", relationship: "depends_on" },
  { from: "CANON-006", to: "CONSTITUTION-ARTICLE-XIII", relationship: "supports" },
  { from: "CANON-009", to: "CONSTITUTION-ARTICLE-XIII", relationship: "supports" },
  { from: "CANON-019", to: "CONSTITUTION-ARTICLE-XIII", relationship: "supports" },
  { from: "CANON-020", to: "CONSTITUTION-ARTICLE-XIII", relationship: "supports" },
  { from: "CANON-022", to: "CONSTITUTION-ARTICLE-XIII", relationship: "supports" },
  { from: "CANON-023", to: "CONSTITUTION-ARTICLE-XIII", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XIII", to: "CONSTITUTION-ARTICLE-XIV", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "CONSTITUTION-ARTICLE-XIII", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "CONSTITUTION-ARTICLE-XI", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "CANON-007", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "CANON-009", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "CANON-015", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "CANON-019", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "CANON-020", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "CANON-022", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "CANON-023", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "CANON-025", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "FRAMEWORK-CHD-001", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "FRAMEWORK-CMD-001", relationship: "supports" },
  { from: "FRAMEWORK-CHD-001", to: "CONSTITUTION-ARTICLE-XIV", relationship: "depends_on" },
  { from: "FRAMEWORK-CHD-001", to: "FRAMEWORK-CMD-001", relationship: "references" },
  { from: "FRAMEWORK-CHD-001", to: "FRAMEWORK-ASR-001", relationship: "references" },
  { from: "FRAMEWORK-CHD-001", to: "FRAMEWORK-LEGACY-001", relationship: "references" },
  { from: "FRAMEWORK-CHD-001", to: "FRAMEWORK-SLP-001", relationship: "references" },
  { from: "FRAMEWORK-CHD-001", to: "constitutional-health", relationship: "supports" },
  { from: "constitutional-health", to: "CONSTITUTION-ARTICLE-XIV", relationship: "depends_on" },
  { from: "FRAMEWORK-CMD-001", to: "CONSTITUTION-ARTICLE-XIV", relationship: "depends_on" },
  { from: "CANON-006", to: "CONSTITUTION-ARTICLE-XIV", relationship: "supports" },
  { from: "CANON-009", to: "CONSTITUTION-ARTICLE-XIV", relationship: "supports" },
  { from: "CANON-015", to: "CONSTITUTION-ARTICLE-XIV", relationship: "supports" },
  { from: "CANON-019", to: "CONSTITUTION-ARTICLE-XIV", relationship: "supports" },
  { from: "CANON-022", to: "CONSTITUTION-ARTICLE-XIV", relationship: "supports" },
  { from: "CANON-025", to: "CONSTITUTION-ARTICLE-XIV", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XIV", to: "CONSTITUTION-ARTICLE-XV", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-XV", to: "CONSTITUTION-ARTICLE-XIV", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XV", to: "CONSTITUTION-ARTICLE-XIII", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XV", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XV", to: "CANON-007", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XV", to: "CANON-016", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XV", to: "CANON-020", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XV", to: "CANON-021", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XV", to: "CANON-023", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XV", to: "CANON-025", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XV", to: "FRAMEWORK-CCR-001", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XV", to: "constitution-schedules", relationship: "supports" },
  { from: "FRAMEWORK-CCR-001", to: "CONSTITUTION-ARTICLE-XV", relationship: "depends_on" },
  { from: "FRAMEWORK-CCR-001", to: "FRAMEWORK-TIA-001", relationship: "references" },
  { from: "FRAMEWORK-CCR-001", to: "FRAMEWORK-GRF-001", relationship: "references" },
  { from: "FRAMEWORK-CCR-001", to: "FRAMEWORK-SLP-001", relationship: "references" },
  { from: "FRAMEWORK-CCR-001", to: "constitution-schedules", relationship: "references" },
  { from: "FRAMEWORK-CCR-001", to: "constitution-centre", relationship: "supports" },
  { from: "constitution-centre", to: "CONSTITUTION-ARTICLE-XV", relationship: "depends_on" },
  { from: "CANON-006", to: "CONSTITUTION-ARTICLE-XV", relationship: "supports" },
  { from: "CANON-007", to: "CONSTITUTION-ARTICLE-XV", relationship: "supports" },
  { from: "CANON-016", to: "CONSTITUTION-ARTICLE-XV", relationship: "supports" },
  { from: "CANON-021", to: "CONSTITUTION-ARTICLE-XV", relationship: "supports" },
  { from: "CANON-025", to: "CONSTITUTION-ARTICLE-XV", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XV", to: "CONSTITUTION-ARTICLE-XVI", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "CONSTITUTION-ARTICLE-XV", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "CONSTITUTION-ARTICLE-V", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "CONSTITUTION-ARTICLE-III", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "CANON-004", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "CANON-009", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "CANON-019", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "CANON-020", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "CANON-023", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "CANON-025", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "FRAMEWORK-CPP-001", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "FRAMEWORK-LGOV-001", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "FRAMEWORK-LSF-001", relationship: "supports" },
  { from: "FRAMEWORK-CPP-001", to: "CONSTITUTION-ARTICLE-XVI", relationship: "depends_on" },
  { from: "FRAMEWORK-CPP-001", to: "FRAMEWORK-LGOV-001", relationship: "references" },
  { from: "FRAMEWORK-CPP-001", to: "FRAMEWORK-LSF-001", relationship: "references" },
  { from: "FRAMEWORK-CPP-001", to: "FRAMEWORK-STEWARDSHIP-PORTAL-001", relationship: "references" },
  { from: "FRAMEWORK-CPP-001", to: "custodian-programme", relationship: "references" },
  { from: "FRAMEWORK-CPP-001", to: "custodian-programme-portal", relationship: "supports" },
  { from: "custodian-programme-portal", to: "CONSTITUTION-ARTICLE-XVI", relationship: "depends_on" },
  { from: "custodian-programme", to: "CONSTITUTION-ARTICLE-XVI", relationship: "depends_on" },
  { from: "CANON-004", to: "CONSTITUTION-ARTICLE-XVI", relationship: "supports" },
  { from: "CANON-006", to: "CONSTITUTION-ARTICLE-XVI", relationship: "supports" },
  { from: "CANON-019", to: "CONSTITUTION-ARTICLE-XVI", relationship: "supports" },
  { from: "CANON-025", to: "CONSTITUTION-ARTICLE-XVI", relationship: "supports" },
  { from: "FRAMEWORK-CTC-001", to: "platform-registry", relationship: "references" },
  { from: "CANON-004", to: "CONSTITUTION-ARTICLE-VIII", relationship: "supports" },
  { from: "CANON-006", to: "CONSTITUTION-ARTICLE-VIII", relationship: "supports" },
  { from: "CANON-016", to: "CONSTITUTION-ARTICLE-VIII", relationship: "supports" },
  { from: "CANON-025", to: "canon-dashboard", relationship: "supports" },
  { from: "custodian-programme", to: "CANON-025", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XVI", to: "CONSTITUTION-ARTICLE-XVII", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-XVII", to: "CONSTITUTION-ARTICLE-XVI", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XVII", to: "CONSTITUTION-ARTICLE-XV", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XVII", to: "CONSTITUTION-ARTICLE-V", relationship: "depends_on" },
  { from: "CONSTITUTION-ARTICLE-XVII", to: "CANON-004", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XVII", to: "CANON-006", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XVII", to: "CANON-007", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XVII", to: "CANON-020", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XVII", to: "CANON-025", relationship: "implements" },
  { from: "CONSTITUTION-ARTICLE-XVII", to: "FRAMEWORK-CCY-001", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XVII", to: "FRAMEWORK-CCR-001", relationship: "supports" },
  { from: "CONSTITUTION-ARTICLE-XVII", to: "FRAMEWORK-CPP-001", relationship: "references" },
  { from: "CONSTITUTION-ARTICLE-XVII", to: "founders-charge", relationship: "supports" },
  { from: "FRAMEWORK-CCY-001", to: "CONSTITUTION-ARTICLE-XVII", relationship: "depends_on" },
  { from: "FRAMEWORK-CCY-001", to: "FRAMEWORK-CCR-001", relationship: "references" },
  { from: "FRAMEWORK-CCY-001", to: "FRAMEWORK-IEC-001", relationship: "references" },
  { from: "FRAMEWORK-CCY-001", to: "constitutional-ceremony-portal", relationship: "supports" },
  { from: "constitutional-ceremony-portal", to: "CONSTITUTION-ARTICLE-XVII", relationship: "depends_on" },
  { from: "founders-charge", to: "CONSTITUTION-ARTICLE-XVII", relationship: "depends_on" },
  { from: "constitution", to: "CONVENTION-VOL-I-001", relationship: "references" },
  { from: "CONVENTION-VOL-I-001", to: "constitution", relationship: "depends_on" },
  { from: "CONVENTION-VOL-I-001", to: "CONSTITUTION-ARTICLE-XV", relationship: "depends_on" },
  { from: "CONVENTION-VOL-I-001", to: "constitutional-convention", relationship: "supports" },
  { from: "constitutional-convention", to: "CONVENTION-VOL-I-001", relationship: "depends_on" },
  { from: "constitution", to: "VOLUME-II-GOVERNANCE-CODE", relationship: "references" },
  { from: "VOLUME-II-GOVERNANCE-CODE", to: "constitution", relationship: "depends_on" },
  { from: "VOLUME-II-GOVERNANCE-CODE", to: "CONSTITUTION-ARTICLE-IV", relationship: "implements" },
  { from: "VOLUME-II-GOVERNANCE-CODE", to: "CONSTITUTION-ARTICLE-V", relationship: "implements" },
  { from: "VOLUME-II-GOVERNANCE-CODE", to: "FRAMEWORK-GC-001", relationship: "supports" },
  { from: "VOLUME-II-GOVERNANCE-CODE", to: "BOOK-I-GOVERNANCE-BODIES", relationship: "supports" },
  { from: "FRAMEWORK-GC-001", to: "VOLUME-II-GOVERNANCE-CODE", relationship: "depends_on" },
  { from: "FRAMEWORK-GC-001", to: "FRAMEWORK-CGOV-001", relationship: "references" },
  { from: "FRAMEWORK-GC-001", to: "FRAMEWORK-LGOV-001", relationship: "references" },
  { from: "FRAMEWORK-GC-001", to: "governance-code-portal", relationship: "supports" },
  { from: "BOOK-I-GOVERNANCE-BODIES", to: "VOLUME-II-GOVERNANCE-CODE", relationship: "depends_on" },
  { from: "BOOK-I-GOVERNANCE-BODIES", to: "CONSTITUTION-ARTICLE-IV", relationship: "implements" },
  { from: "governance-code-portal", to: "VOLUME-II-GOVERNANCE-CODE", relationship: "depends_on" },
  { from: "FRAMEWORK-SLP-001", to: "FRAMEWORK-LIB-SESS-001", relationship: "supports" },
  { from: "FRAMEWORK-LIB-SESS-001", to: "FRAMEWORK-SLP-001", relationship: "depends_on" },
  { from: "FRAMEWORK-LIB-SESS-001", to: "library-sessions", relationship: "supports" },
  { from: "FRAMEWORK-LIB-SESS-001", to: "LIB-2026-06-27-001", relationship: "references" },
  { from: "FRAMEWORK-LIB-SESS-001", to: "LIB-2026-06-27-002", relationship: "references" },
  { from: "LIB-2026-06-27-001", to: "VOLUME-II-GOVERNANCE-CODE", relationship: "references" },
  { from: "LIB-2026-06-27-001", to: "constitutional-convention", relationship: "references" },
  { from: "LIB-2026-06-27-002", to: "FRAMEWORK-LIB-SESS-001", relationship: "implements" },
  { from: "library-sessions", to: "FRAMEWORK-LIB-SESS-001", relationship: "depends_on" },
  { from: "FRAMEWORK-LIB-SESS-001", to: "FRAMEWORK-EDW-001", relationship: "supports" },
  { from: "FRAMEWORK-EDW-001", to: "FRAMEWORK-LIB-SESS-001", relationship: "depends_on" },
  { from: "FRAMEWORK-EDW-001", to: "FRAMEWORK-SLP-001", relationship: "depends_on" },
  { from: "FRAMEWORK-EDW-001", to: "editorial-standards", relationship: "supports" },
  { from: "editorial-standards", to: "FRAMEWORK-EDW-001", relationship: "depends_on" },
  { from: "VOLUME-II-GOVERNANCE-CODE", to: "FRAMEWORK-EDW-001", relationship: "references" },
  { from: "constitution", to: "FRAMEWORK-EDW-001", relationship: "references" },
  { from: "LIB-2026-06-27-003", to: "FRAMEWORK-EDW-001", relationship: "implements" },
  { from: "FRAMEWORK-EDW-001", to: "LIB-2026-06-27-003", relationship: "references" },
  { from: "LIB-2026-06-27-004", to: "BOOK-I-ARCHITECTURE", relationship: "implements" },
  { from: "BOOK-I-ARCHITECTURE", to: "VOLUME-II-GOVERNANCE-CODE", relationship: "depends_on" },
  { from: "BOOK-I-ARCHITECTURE", to: "LIB-2026-06-27-004", relationship: "references" },
  { from: "LIB-2026-06-27-005", to: "BOOK-I-ARCHITECTURE", relationship: "implements" },
  { from: "BOOK-I-ARCHITECTURE", to: "LIB-2026-06-27-005", relationship: "references" },
  { from: "LIB-2026-06-27-006", to: "BOOK-I-ARCHITECTURE", relationship: "implements" },
  { from: "LIB-2026-06-27-006", to: "FRAMEWORK-LPS-001", relationship: "implements" },
  { from: "FRAMEWORK-SLPS-001", to: "FRAMEWORK-LPS-001", relationship: "supersedes" },
  { from: "FRAMEWORK-LPS-001", to: "FRAMEWORK-SLPS-001", relationship: "aliases" },
  { from: "LIB-2026-06-27-007", to: "FRAMEWORK-SLPS-001", relationship: "implements" },
  { from: "LIB-2026-06-27-007", to: "PUB-ENGINE-001", relationship: "implements" },
  { from: "PUB-ENGINE-001", to: "FRAMEWORK-SLPS-001", relationship: "depends_on" },
  { from: "FRAMEWORK-SLPS-001", to: "FRAMEWORK-EDW-001", relationship: "depends_on" },
  { from: "FRAMEWORK-EDW-001", to: "FRAMEWORK-SLPS-001", relationship: "supports" },
  { from: "FRAMEWORK-SLPS-001", to: "editorial-standards", relationship: "supports" },
  { from: "PUB-ENGINE-001", to: "editorial-standards", relationship: "supports" },
  { from: "BOOK-I-ARCHITECTURE", to: "FRAMEWORK-SLPS-001", relationship: "references" },
  { from: "LIB-2026-06-27-008", to: "FRAMEWORK-SLPS-CORE-001", relationship: "implements" },
  { from: "FRAMEWORK-SLPS-CORE-001", to: "FRAMEWORK-SLPS-001", relationship: "enforces" },
  { from: "FRAMEWORK-SLPS-CORE-001", to: "PUB-ENGINE-001", relationship: "includes" },
  { from: "FRAMEWORK-SLPS-CORE-001", to: "FRAMEWORK-EDW-001", relationship: "depends_on" },
  { from: "FRAMEWORK-SLPS-CORE-001", to: "editorial-standards", relationship: "supports" },
  { from: "FRAMEWORK-SLPS-CORE-001", to: "slps-core", relationship: "implements" },
  { from: "PUB-ENGINE-001", to: "FRAMEWORK-SLPS-CORE-001", relationship: "part_of" },
  { from: "BOOK-I-ARCHITECTURE", to: "FRAMEWORK-SLPS-CORE-001", relationship: "references" },
  { from: "LIB-2026-07-03-013", to: "FOUNDER-INSIGHT-001", relationship: "implements" },
  { from: "FOUNDER-INSIGHT-001", to: "LIB-2026-07-03-013", relationship: "references" },
  { from: "FOUNDER-INSIGHT-001", to: "CANON-002", relationship: "references" },
  { from: "FOUNDER-INSIGHT-001", to: "CANON-004", relationship: "references" },
  { from: "FOUNDER-INSIGHT-001", to: "CANON-006", relationship: "references" },
  { from: "FOUNDER-INSIGHT-001", to: "FRAMEWORK-CPP-001", relationship: "supports" },
  { from: "LIB-2026-06-27-012", to: "BOOK-I-CH-01-ARCHITECTURE", relationship: "implements" },
  { from: "BOOK-I-CH-01-ARCHITECTURE", to: "LIB-2026-06-27-012", relationship: "references" },
  { from: "BOOK-I-CH-01-ARCHITECTURE", to: "FRAMEWORK-CEF-001", relationship: "conforms_to" },
  { from: "BOOK-I-CH-01-ARCHITECTURE", to: "BOOK-I-FOUNDATIONAL-CHARTER", relationship: "depends_on" },
  { from: "FRAMEWORK-CEF-001", to: "FRAMEWORK-SLPS-001", relationship: "part_of" },
  { from: "LIB-2026-06-27-012", to: "FRAMEWORK-CEF-001", relationship: "implements" },
  { from: "LIB-2026-06-27-011", to: "BOOK-I-FOUNDATIONAL-CHARTER", relationship: "implements" },
  { from: "BOOK-I-FOUNDATIONAL-CHARTER", to: "LIB-2026-06-27-011", relationship: "references" },
  { from: "LIB-2026-06-27-010", to: "BOOK-I-FOUNDATIONAL-CHARTER", relationship: "implements" },
  { from: "FRAMEWORK-FC-001", to: "FRAMEWORK-SLPS-001", relationship: "part_of" },
  { from: "BOOK-I-FOUNDATIONAL-CHARTER", to: "FRAMEWORK-FC-001", relationship: "conforms_to" },
  { from: "BOOK-I-FOUNDATIONAL-CHARTER", to: "BOOK-I-CHARTER", relationship: "supersedes" },
  { from: "LIB-2026-06-27-009", to: "BOOK-I-FOUNDATIONAL-CHARTER", relationship: "references" },
  { from: "BOOK-I-CHARTER", to: "BOOK-I-ARCHITECTURE", relationship: "depends_on" },
  { from: "BOOK-I-FOUNDATIONAL-CHARTER", to: "BOOK-I-ARCHITECTURE", relationship: "depends_on" },
  { from: "BOOK-I-CHARTER", to: "FRAMEWORK-SLPS-001", relationship: "conforms_to" },
  { from: "BOOK-I-CHARTER", to: "VOLUME-II-GOVERNANCE-CODE", relationship: "part_of" },
  { from: "LIB-2026-06-27-009", to: "BOOK-I-ARCHITECTURE", relationship: "references" },
  { from: "FRAMEWORK-LPS-001", to: "FRAMEWORK-EDW-001", relationship: "depends_on" },
  { from: "FRAMEWORK-EDW-001", to: "FRAMEWORK-LPS-001", relationship: "supports" },
  { from: "FRAMEWORK-LPS-001", to: "editorial-standards", relationship: "supports" },
  { from: "BOOK-I-ARCHITECTURE", to: "FRAMEWORK-LPS-001", relationship: "references" },
  { from: "FRAMEWORK-EDW-001", to: "BOOK-I-ARCHITECTURE", relationship: "supports" },
  { from: "CANON-004", to: "CONSTITUTION-ARTICLE-XVII", relationship: "supports" },
  { from: "CANON-025", to: "CONSTITUTION-ARTICLE-XVII", relationship: "supports" },
  { from: "CANON-005", to: "yike", relationship: "applied_in" },
  { from: "CANON-005", to: "stanhan", relationship: "applied_in" },
  { from: "CANON-005", to: "stankings-auto-hub", relationship: "applied_in" },
  { from: "CANON-005", to: "bayright", relationship: "applied_in" },
  { from: "yike", to: "stanhan", relationship: "supports" },
  { from: "yike", to: "stankings-auto-hub", relationship: "supports" },
  { from: "yike", to: "bayright", relationship: "depends_on" },
  { from: "stankings-auto-hub", to: "yike", relationship: "supports" },
  { from: "stanhan", to: "yike", relationship: "supports" },
  { from: "CANON-002", to: "constitution", relationship: "references" },
  { from: "CANON-002", to: "engineering", relationship: "applied_in" },
  { from: "CANON-002", to: "bayright", relationship: "applied_in" },
  { from: "CANON-002", to: "yike", relationship: "applied_in" },
  { from: "yike", to: "passport", relationship: "implements" },
  { from: "passport", to: "verification", relationship: "depends_on" },
  { from: "bayright", to: "escrow", relationship: "implements" },
  { from: "verification", to: "escrow", relationship: "supports" },
  { from: "escrow", to: "ai", relationship: "references" },
  { from: "ai", to: "support", relationship: "supports" },
];

export function getGraphNeighborhood(nodeId: string, depth = 2) {
  const visited = new Set<string>([nodeId]);
  const edges: GraphEdge[] = [];
  let frontier = [nodeId];

  for (let d = 0; d < depth; d++) {
    const next: string[] = [];
    for (const id of frontier) {
      for (const edge of INSTITUTIONAL_GRAPH_EDGES) {
        if (edge.from === id && !visited.has(edge.to)) {
          visited.add(edge.to);
          next.push(edge.to);
          edges.push(edge);
        }
        if (edge.to === id && !visited.has(edge.from)) {
          visited.add(edge.from);
          next.push(edge.from);
          edges.push(edge);
        }
      }
    }
    frontier = next;
  }

  const nodes = INSTITUTIONAL_GRAPH_NODES.filter((n) => visited.has(n.id));
  return { nodes, edges, root: nodeId };
}

export function searchGraph(query: string): GraphNode[] {
  const q = query.toLowerCase();
  return INSTITUTIONAL_GRAPH_NODES.filter(
    (n) => n.label.toLowerCase().includes(q) || n.id.toLowerCase().includes(q)
  );
}
