/**
 * Canon Dashboard — living bridge between Volume 0 philosophy and implementation
 */

export type CanonImplementationStatus = "active" | "in_progress" | "planned";

export interface CanonDashboardRow {
  canonId: string;
  canonTitle: string;
  canonHref: string;
  framework?: string;
  frameworkHref?: string;
  platformFeature: string;
  platformHref?: string;
  status: CanonImplementationStatus;
  category: string;
}

export const CANON_DASHBOARD_ROWS: CanonDashboardRow[] = [
  {
    canonId: "CANON-001",
    canonTitle: "Institutions Exist to Serve",
    canonHref: "/library/canon/CANON-001",
    platformFeature: "Customer Journey Maps",
    platformHref: "/library/ecosystem",
    status: "active",
    category: "Moral Foundation",
  },
  {
    canonId: "CANON-002",
    canonTitle: "Trust Is Institutional Capital",
    canonHref: "/library/canon/CANON-002",
    framework: "Trust Impact Assessment",
    frameworkHref: "/library/frameworks/trust-impact-assessment",
    platformFeature: "Trust Engine",
    status: "active",
    category: "Moral Foundation",
  },
  {
    canonId: "CANON-003",
    canonTitle: "Every Institution Must Know Its Purpose",
    canonHref: "/library/canon/CANON-003",
    framework: "Purpose Assessment",
    frameworkHref: "/library/frameworks/purpose-assessment",
    platformFeature: "Proposal Workflow",
    status: "active",
    category: "Moral Foundation",
  },
  {
    canonId: "CANON-004",
    canonTitle: "Leadership Is Stewardship",
    canonHref: "/library/canon/CANON-004",
    framework: "Leadership Stewardship Framework",
    frameworkHref: "/library/frameworks/leadership-stewardship",
    platformFeature: "Leadership Portal",
    status: "active",
    category: "Moral Foundation",
  },
  {
    canonId: "CANON-005",
    canonTitle: "The Ecosystem Is Greater Than Any Single Institution",
    canonHref: "/library/canon/CANON-005",
    framework: "Ecosystem Impact Assessment",
    frameworkHref: "/library/frameworks/ecosystem-impact-assessment",
    platformFeature: "Ecosystem Map",
    platformHref: "/library/ecosystem",
    status: "active",
    category: "Moral Foundation",
  },
  {
    canonId: "CANON-006",
    canonTitle: "Think in Generations, Act in the Present",
    canonHref: "/library/canon/CANON-006",
    framework: "Generational Review",
    frameworkHref: "/library/frameworks/generational-review",
    platformFeature: "Strategy Module",
    status: "active",
    category: "Moral Foundation",
  },
  {
    canonId: "CANON-007",
    canonTitle: "Truth Is Non-Negotiable",
    canonHref: "/library/canon/CANON-007",
    framework: "Institutional Decision Record",
    frameworkHref: "/library/frameworks/institutional-decision-record",
    platformFeature: "Decision Registry",
    platformHref: "/library/decisions",
    status: "active",
    category: "Moral Foundation",
  },
  {
    canonId: "CANON-008",
    canonTitle: "Excellence Is a Discipline, Not an Event",
    canonHref: "/library/canon/CANON-008",
    framework: "Excellence Framework",
    frameworkHref: "/library/frameworks/excellence",
    platformFeature: "Quality Dashboard",
    platformHref: "/library/excellence",
    status: "active",
    category: "Moral Foundation",
  },
  {
    canonId: "CANON-009",
    canonTitle: "Learn Continuously, Improve Deliberately",
    canonHref: "/library/canon/CANON-009",
    framework: "Lessons Learned Review",
    frameworkHref: "/library/frameworks/lessons-learned",
    platformFeature: "Knowledge Engine",
    platformHref: "/library/lessons",
    status: "active",
    category: "Moral Foundation",
  },
  {
    canonId: "CANON-010",
    canonTitle: "People Are Ends, Never Merely Means",
    canonHref: "/library/canon/CANON-010",
    framework: "Human Impact Review",
    frameworkHref: "/library/frameworks/human-impact-review",
    platformFeature: "UX & Policy Reviews",
    status: "active",
    category: "Moral Foundation",
  },
  {
    canonId: "CANON-011",
    canonTitle: "Simplicity Creates Strength",
    canonHref: "/library/canon/CANON-011",
    framework: "Simplicity Review",
    frameworkHref: "/library/frameworks/simplicity-review",
    platformFeature: "Engineering Review",
    status: "active",
    category: "Operational",
  },
  {
    canonId: "CANON-012",
    canonTitle: "Build Platforms, Not Silos",
    canonHref: "/library/canon/CANON-012",
    framework: "Platform Assessment",
    frameworkHref: "/library/frameworks/platform-assessment",
    platformFeature: "Platform Registry",
    platformHref: "/library/platforms",
    status: "active",
    category: "Architectural",
  },
  {
    canonId: "CANON-013",
    canonTitle: "Innovate with Purpose",
    canonHref: "/library/canon/CANON-013",
    framework: "Innovation Governance",
    frameworkHref: "/library/frameworks/innovation-governance",
    platformFeature: "Innovation Hub",
    status: "active",
    category: "Innovation",
  },
  {
    canonId: "CANON-014",
    canonTitle: "Our Word Is a Commitment",
    canonHref: "/library/canon/CANON-014",
    framework: "Commitment Registry",
    platformFeature: "Public Commitments",
    platformHref: "/library/commitments",
    status: "active",
    category: "Credibility",
  },
  {
    canonId: "CANON-015",
    canonTitle: "Accountability Builds Resilience",
    canonHref: "/library/canon/CANON-015",
    framework: "Incident & Accountability Framework",
    frameworkHref: "/library/frameworks/incident-accountability",
    platformFeature: "Incident Center",
    platformHref: "/library/incidents",
    status: "active",
    category: "Resilience",
  },
  {
    canonId: "CANON-016",
    canonTitle: "Build for Institutional Strength",
    canonHref: "/library/canon/CANON-016",
    framework: "Institutional Strength Assessment",
    frameworkHref: "/library/frameworks/institutional-strength-assessment",
    platformFeature: "Strength Assessment",
    status: "active",
    category: "Strategic",
  },
  {
    canonId: "CANON-017",
    canonTitle: "Reduce Uncertainty",
    canonHref: "/library/canon/CANON-017",
    framework: "Uncertainty Reduction Framework",
    frameworkHref: "/library/frameworks/uncertainty-reduction",
    platformFeature: "Confidence Mapping",
    platformHref: "/library/ecosystem",
    status: "active",
    category: "Strategic",
  },
  {
    canonId: "CANON-018",
    canonTitle: "Principles Before Opportunity",
    canonHref: "/library/canon/CANON-018",
    framework: "Principles Alignment Review",
    frameworkHref: "/library/frameworks/principles-alignment-review",
    platformFeature: "Canon Alignment Matrix",
    status: "active",
    category: "Strategic",
  },
  {
    canonId: "CANON-019",
    canonTitle: "Leave It Better Than You Found It",
    canonHref: "/library/canon/CANON-019",
    framework: "Institutional Improvement Register",
    frameworkHref: "/library/improvements",
    platformFeature: "Annual Stewardship Review",
    platformHref: "/library/frameworks/annual-stewardship-review",
    status: "active",
    category: "Legacy",
  },
  {
    canonId: "CANON-020",
    canonTitle: "Exercise Sound Judgment",
    canonHref: "/library/canon/CANON-020",
    framework: "Institutional Decision Intelligence",
    frameworkHref: "/library/decision-intelligence",
    platformFeature: "Judgment Records",
    platformHref: "/library/decision-intelligence",
    status: "active",
    category: "Legacy",
  },
  {
    canonId: "CANON-021",
    canonTitle: "Knowledge Is an Institutional Asset",
    canonHref: "/library/canon/CANON-021",
    framework: "Institutional Knowledge Graph",
    frameworkHref: "/library/knowledge-graph",
    platformFeature: "Connected Knowledge",
    platformHref: "/library/knowledge-graph",
    status: "active",
    category: "Legacy",
  },
  {
    canonId: "CANON-022",
    canonTitle: "Create Value That Outlasts Us",
    canonHref: "/library/canon/CANON-022",
    framework: "Legacy Dashboard",
    frameworkHref: "/library/legacy",
    platformFeature: "Annual Stewardship Reports",
    platformHref: "/library/legacy",
    status: "active",
    category: "Civilization",
  },
  {
    canonId: "CANON-023",
    canonTitle: "Remain Humble Enough to Learn",
    canonHref: "/library/canon/CANON-023",
    framework: "Knowledge Challenge Process",
    frameworkHref: "/library/knowledge-challenges",
    platformFeature: "Knowledge Challenges",
    platformHref: "/library/knowledge-challenges",
    status: "active",
    category: "Civilization",
  },
  {
    canonId: "CANON-024",
    canonTitle: "Raise the Standard",
    canonHref: "/library/canon/CANON-024",
    framework: "Industry Leadership Dashboard",
    frameworkHref: "/library/industry-leadership",
    platformFeature: "Industry Standards",
    platformHref: "/library/industry-leadership",
    status: "active",
    category: "Civilization",
  },
  {
    canonId: "CANON-025",
    canonTitle: "Be Worthy of Endurance",
    canonHref: "/library/canon/CANON-025",
    framework: "Canon Maturity Dashboard",
    frameworkHref: "/library/canon-maturity",
    platformFeature: "Volume 0 Maturity",
    platformHref: "/library/canon-maturity",
    status: "active",
    category: "Volume 0 Capstone",
  },
];

export function getCanonDashboardStats() {
  const total = CANON_DASHBOARD_ROWS.length;
  const active = CANON_DASHBOARD_ROWS.filter((r) => r.status === "active").length;
  const inProgress = CANON_DASHBOARD_ROWS.filter((r) => r.status === "in_progress").length;
  return { total, active, inProgress, planned: total - active - inProgress };
}
