import type { LexiconReference, LexiconTerm } from "@/lib/lexicon-engine/types";

function approvedVersion(
  term: Omit<LexiconTerm, "versions">,
  summary = "First approved definition under LS-002 v1.0"
): LexiconTerm["versions"] {
  return [
    {
      version: term.version,
      date: term.approvedAt,
      summaryOfChanges: summary,
      definition: [term.definition, ...term.paragraphs].join("\n\n"),
      approvalStatus: "approved",
      author: term.author,
    },
  ];
}

const SHARED_REFS = {
  canon001: {
    identifier: "CANON-001",
    title: "Institutions Exist to Serve",
    objectType: "canon",
    href: "/library/canon/CANON-001",
  } satisfies LexiconReference,
  canon002: {
    identifier: "CANON-002",
    title: "Trust Is Institutional Capital",
    objectType: "canon",
    href: "/library/canon/CANON-002",
  } satisfies LexiconReference,
  canon004: {
    identifier: "CANON-004",
    title: "Leadership Is Stewardship",
    objectType: "canon",
    href: "/library/canon/CANON-004",
  } satisfies LexiconReference,
  canon005: {
    identifier: "CANON-005",
    title: "The Ecosystem Is Greater Than Any Single Institution",
    objectType: "canon",
    href: "/library/canon/CANON-005",
  } satisfies LexiconReference,
  canon006: {
    identifier: "CANON-006",
    title: "Think in Generations, Act in the Present",
    objectType: "canon",
    href: "/library/canon/CANON-006",
  } satisfies LexiconReference,
  canon007: {
    identifier: "CANON-007",
    title: "Truth Before Convenience",
    objectType: "canon",
    href: "/library/canon/CANON-007",
  } satisfies LexiconReference,
  canon008: {
    identifier: "CANON-008",
    title: "Excellence Is a Discipline, Not an Event",
    objectType: "canon",
    href: "/library/canon/CANON-008",
  } satisfies LexiconReference,
  canon009: {
    identifier: "CANON-009",
    title: "Learn Continuously, Improve Deliberately",
    objectType: "canon",
    href: "/library/canon/CANON-009",
  } satisfies LexiconReference,
  canon010: {
    identifier: "CANON-010",
    title: "People Are Ends, Never Merely Means",
    objectType: "canon",
    href: "/library/canon/CANON-010",
  } satisfies LexiconReference,
  canon011: {
    identifier: "CANON-011",
    title: "Simplicity Creates Strength",
    objectType: "canon",
    href: "/library/canon/CANON-011",
  } satisfies LexiconReference,
  canon012: {
    identifier: "CANON-012",
    title: "Build Platforms, Not Silos",
    objectType: "canon",
    href: "/library/canon/CANON-012",
  } satisfies LexiconReference,
  canon013: {
    identifier: "CANON-013",
    title: "Innovate with Purpose",
    objectType: "canon",
    href: "/library/canon/CANON-013",
  } satisfies LexiconReference,
  canon014: {
    identifier: "CANON-014",
    title: "Our Word Is a Commitment",
    objectType: "canon",
    href: "/library/canon/CANON-014",
  } satisfies LexiconReference,
  canon015: {
    identifier: "CANON-015",
    title: "Accountability Builds Resilience",
    objectType: "canon",
    href: "/library/canon/CANON-015",
  } satisfies LexiconReference,
  canon016: {
    identifier: "CANON-016",
    title: "Build for Institutional Strength",
    objectType: "canon",
    href: "/library/canon/CANON-016",
  } satisfies LexiconReference,
  canon017: {
    identifier: "CANON-017",
    title: "Reduce Uncertainty",
    objectType: "canon",
    href: "/library/canon/CANON-017",
  } satisfies LexiconReference,
  canon018: {
    identifier: "CANON-018",
    title: "Principles Before Opportunity",
    objectType: "canon",
    href: "/library/canon/CANON-018",
  } satisfies LexiconReference,
  canon019: {
    identifier: "CANON-019",
    title: "Leave It Better Than You Found It",
    objectType: "canon",
    href: "/library/canon/CANON-019",
  } satisfies LexiconReference,
  canon020: {
    identifier: "CANON-020",
    title: "Exercise Sound Judgment",
    objectType: "canon",
    href: "/library/canon/CANON-020",
  } satisfies LexiconReference,
  canon021: {
    identifier: "CANON-021",
    title: "Knowledge Is an Institutional Asset",
    objectType: "canon",
    href: "/library/canon/CANON-021",
  } satisfies LexiconReference,
  canon022: {
    identifier: "CANON-022",
    title: "Create Value That Outlasts Us",
    objectType: "canon",
    href: "/library/canon/CANON-022",
  } satisfies LexiconReference,
  canon023: {
    identifier: "CANON-023",
    title: "Remain Humble Enough to Learn",
    objectType: "canon",
    href: "/library/canon/CANON-023",
  } satisfies LexiconReference,
  canon024: {
    identifier: "CANON-024",
    title: "Raise the Standard",
    objectType: "canon",
    href: "/library/canon/CANON-024",
  } satisfies LexiconReference,
  canon025: {
    identifier: "CANON-025",
    title: "Be Worthy of Endurance",
    objectType: "canon",
    href: "/library/canon/CANON-025",
  } satisfies LexiconReference,
  tia: {
    identifier: "FRAMEWORK-TIA-001",
    title: "Trust Impact Assessment Framework",
    objectType: "framework",
    href: "/library/frameworks/trust-impact-assessment",
  } satisfies LexiconReference,
  ls001: {
    identifier: "LS-001",
    title: "The Knowledge Object Standard",
    objectType: "standard",
    href: "/library/standards/ls-001",
  } satisfies LexiconReference,
  ls002: {
    identifier: "LS-002",
    title: "The Stankings Lexicon",
    objectType: "standard",
    href: "/library/standards/ls-002",
  } satisfies LexiconReference,
  constitution: {
    identifier: "constitution",
    title: "The Constitution — Volume I",
    objectType: "volume",
    href: "/library/constitution",
  } satisfies LexiconReference,
  firstPrinciples: {
    identifier: "volume-0",
    title: "The First Principles — Volume 0",
    objectType: "volume",
    href: "/library/first-principles",
  } satisfies LexiconReference,
};

/** Authoritative LS-002 v1.0 approved terms */
const STATIC_LEXICON_TERM_DRAFTS: Omit<LexiconTerm, "versions">[] = [
  {
    identifier: "LEX-INSTITUTION",
    term: "Institution",
    slug: "institution",
    letter: "I",
    definition:
      "An enduring organization established to solve meaningful problems, preserve trust and create lasting value for society across generations.",
    paragraphs: ["Institutions exist to outlive individuals."],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["organization", "enduring enterprise"],
    relatedTermSlugs: ["stewardship", "custodian", "legacy", "ecosystem", "trust"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon001, SHARED_REFS.constitution, SHARED_REFS.firstPrinciples],
    searchKeywords: ["institution", "enduring", "organization", "generations"],
  },
  {
    identifier: "LEX-STEWARDSHIP",
    term: "Stewardship",
    slug: "stewardship",
    letter: "S",
    definition:
      "The responsible care, preservation and improvement of something entrusted to one's leadership.",
    paragraphs: [
      "Stewardship rejects ownership mentality.",
      "Every custodian receives the institution temporarily and must leave it stronger than it was found.",
    ],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["guardianship", "responsible care"],
    relatedTermSlugs: ["custodian", "institution", "legacy", "continuous-customer-stewardship"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon001, SHARED_REFS.canon004, SHARED_REFS.canon006, SHARED_REFS.constitution],
    searchKeywords: ["stewardship", "care", "preservation", "custodian"],
  },
  {
    identifier: "LEX-TRUST",
    term: "Trust",
    slug: "trust",
    letter: "T",
    definition:
      "The confidence earned through consistent integrity, competence, transparency and accountability.",
    paragraphs: [
      "Trust is the greatest institutional asset of Stankings Group.",
      "Trust cannot be purchased.",
      "It must be earned repeatedly.",
    ],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["confidence", "credibility"],
    relatedTermSlugs: ["customer", "excellence", "institution"],
    referencedBy: [
      SHARED_REFS.ls002,
      SHARED_REFS.canon001,
      SHARED_REFS.canon002,
      SHARED_REFS.tia,
      SHARED_REFS.constitution,
    ],
    searchKeywords: ["trust", "integrity", "accountability", "transparency"],
  },
  {
    identifier: "LEX-TRUTH",
    term: "Truth",
    slug: "truth",
    letter: "T",
    definition:
      "Accurate information, intellectual honesty and the courage to confront reality in reporting, communication and decision-making.",
    paragraphs: [
      "Truth before convenience — evidence over assumption, understanding over opinion.",
      "Institutional learning begins with institutional honesty.",
    ],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["reality", "evidence", "honesty"],
    relatedTermSlugs: ["trust", "single-source-of-truth", "excellence"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon007],
    searchKeywords: ["truth", "honesty", "evidence", "reality", "transparency"],
  },
  {
    identifier: "LEX-CUSTODIAN",
    term: "Custodian",
    slug: "custodian",
    letter: "C",
    definition:
      "An individual entrusted with protecting, improving and passing the institution to future generations.",
    paragraphs: [
      "Custodians do not inherit privilege.",
      "They inherit responsibility.",
    ],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["steward", "successor leader"],
    relatedTermSlugs: ["stewardship", "institution", "legacy"],
    distinctions: [
      { term: "Employee", when: "When describing employment relationship and compensation." },
      { term: "Founder", when: "When describing origin authority — never permanent ownership." },
    ],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon001, SHARED_REFS.canon004, SHARED_REFS.canon006, SHARED_REFS.firstPrinciples],
    searchKeywords: ["custodian", "successor", "leadership", "responsibility"],
  },
  {
    identifier: "LEX-CUSTOMER",
    term: "Customer",
    slug: "customer",
    letter: "C",
    definition:
      "Any individual, family, business, institution or community that chooses to engage with one or more organizations within the Stankings ecosystem.",
    paragraphs: [
      "Customers are never viewed merely as transactions.",
      "They are people who have placed trust in the institution.",
    ],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["client", "user"],
    relatedTermSlugs: ["trust", "ecosystem", "continuous-customer-stewardship"],
    distinctions: [
      { term: "Member", when: "When describing Stankings Passport or institutional membership." },
      { term: "Partner", when: "When describing contractual or strategic alignment." },
      { term: "Beneficiary", when: "When describing Foundation or social impact recipients." },
    ],
    referencedBy: [SHARED_REFS.ls002],
    searchKeywords: ["customer", "client", "engagement", "ecosystem"],
  },
  {
    identifier: "LEX-ECOSYSTEM",
    term: "Ecosystem",
    slug: "ecosystem",
    letter: "E",
    definition:
      "The coordinated network of institutions, technologies, people and shared capabilities operating together under the principles of Stankings Group.",
    paragraphs: [
      "The ecosystem exists to create outcomes greater than any single institution could achieve independently.",
    ],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["network", "institutional family"],
    relatedTermSlugs: ["institution", "capability", "institutional-reinforcement", "customer"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon005],
    searchKeywords: ["ecosystem", "network", "institutions", "capabilities"],
  },
  {
    identifier: "LEX-CAPABILITY",
    term: "Capability",
    slug: "capability",
    letter: "C",
    definition:
      "A unique competence deliberately developed to strengthen both an individual institution and the wider ecosystem.",
    paragraphs: ["Capabilities are shared where doing so increases institutional effectiveness."],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["competence", "institutional strength"],
    relatedTermSlugs: ["ecosystem", "excellence", "institutional-reinforcement"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon005],
    searchKeywords: ["capability", "competence", "shared", "ecosystem"],
  },
  {
    identifier: "LEX-EXCELLENCE",
    term: "Excellence",
    slug: "excellence",
    letter: "E",
    definition:
      "The disciplined pursuit of consistently high standards through continuous improvement, professional competence and ethical conduct.",
    paragraphs: ["Excellence is a habit rather than an event."],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["high standards", "disciplined quality"],
    relatedTermSlugs: ["trust", "stewardship", "capability"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon001, SHARED_REFS.canon008],
    searchKeywords: ["excellence", "standards", "improvement", "ethics"],
  },
  {
    identifier: "LEX-LEGACY",
    term: "Legacy",
    slug: "legacy",
    letter: "L",
    definition: "The enduring value intentionally preserved for future generations.",
    paragraphs: [
      "Legacy includes institutions, knowledge, culture, reputation, relationships and opportunities.",
      "Legacy is measured by what remains useful after the present generation has passed.",
    ],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["enduring value", "generational inheritance"],
    relatedTermSlugs: ["institution", "custodian", "stewardship", "learning"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon001, SHARED_REFS.canon006, SHARED_REFS.canon022],
    searchKeywords: ["legacy", "generations", "enduring", "inheritance"],
  },
  {
    identifier: "LEX-LEARNING",
    term: "Learning",
    slug: "learning",
    letter: "L",
    definition:
      "The continuous institutional discipline of transforming experience into knowledge that improves judgment and strengthens capability.",
    paragraphs: [
      "Learning is not an event or training session alone.",
      "It is how institutions remain relevant across changing markets, technology and generations.",
    ],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["continuous improvement", "institutional learning", "lessons learned"],
    relatedTermSlugs: ["excellence", "truth", "knowledge-object", "legacy"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon009],
    searchKeywords: ["learning", "lessons", "improvement", "retrospective", "knowledge"],
  },
  {
    identifier: "LEX-DIGNITY",
    term: "Dignity",
    slug: "dignity",
    letter: "D",
    definition:
      "The inherent worth of every person, which institutions shall respect in every policy, product and interaction.",
    paragraphs: [
      "Dignity is not earned by title, wealth or influence.",
      "People are ends, never merely means to institutional objectives.",
    ],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["respect", "human worth", "fair treatment"],
    relatedTermSlugs: ["trust", "customer", "excellence", "learning"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon001, SHARED_REFS.canon010],
    searchKeywords: ["dignity", "respect", "fairness", "people", "human impact"],
  },
  {
    identifier: "LEX-KNOWLEDGE-OBJECT",
    term: "Knowledge Object",
    slug: "knowledge-object",
    letter: "K",
    definition:
      "The smallest authoritative unit of institutional knowledge within the Stankings Library.",
    paragraphs: [
      "Knowledge Objects may include Canons, Articles, Policies, Standards, Procedures, Decisions, Frameworks and other approved forms of institutional knowledge.",
      "Every Knowledge Object shall possess one authoritative source.",
    ],
    status: "approved",
    version: "1.0",
    author: "Library Council",
    approver: "Stanley Ukeje",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["knowledge unit", "library object"],
    relatedTermSlugs: ["single-source-of-truth"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.ls001],
    searchKeywords: ["knowledge object", "LS-001", "canon", "standard", "metadata"],
  },
  {
    identifier: "LEX-SINGLE-SOURCE-OF-TRUTH",
    term: "Single Source of Truth",
    slug: "single-source-of-truth",
    letter: "S",
    definition:
      "The principle that every institutional concept, policy, standard or governing idea shall have one authoritative record within the Stankings Library.",
    paragraphs: ["All other documents shall reference that source rather than duplicate it."],
    status: "approved",
    version: "1.0",
    author: "Library Council",
    approver: "Stanley Ukeje",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["SSOT", "authoritative source"],
    relatedTermSlugs: ["knowledge-object"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.ls001, SHARED_REFS.constitution],
    searchKeywords: ["single source of truth", "SSOT", "authoritative", "duplicate"],
  },
  {
    identifier: "LEX-SIMPLICITY",
    term: "Simplicity",
    slug: "simplicity",
    letter: "S",
    definition:
      "The disciplined removal of unnecessary complexity so that what is essential may perform exceptionally well.",
    paragraphs: [
      "Simplicity is not superficiality.",
      "Complexity shall require justification; simplicity is the default.",
    ],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["clarity", "elegance", "thoughtful design"],
    relatedTermSlugs: ["knowledge-object", "single-source-of-truth", "excellence"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon011],
    searchKeywords: ["simplicity", "clarity", "complexity", "design", "maintainability"],
  },
  {
    identifier: "LEX-PLATFORM",
    term: "Platform",
    slug: "platform",
    letter: "P",
    definition:
      "A shared institutional capability — owned, governed, and consumed across the ecosystem rather than rebuilt in every company.",
    paragraphs: [
      "Platforms create leverage. Silos create duplication.",
      "Before building, consult the Platform Registry and complete a Platform Assessment.",
    ],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["shared platform", "institutional platform", "ecosystem platform"],
    relatedTermSlugs: ["ecosystem", "single-source-of-truth", "simplicity"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon012],
    searchKeywords: ["platform", "shared infrastructure", "silos", "reuse", "ecosystem"],
  },
  {
    identifier: "LEX-INNOVATION",
    term: "Innovation",
    slug: "innovation",
    letter: "I",
    definition:
      "The disciplined pursuit of new methods, technologies and capabilities to solve meaningful problems — guided by purpose, not novelty alone.",
    paragraphs: [
      "Innovation is a means. Purpose is the end.",
      "Significant innovation shall begin as a controlled experiment and pass the Innovation Governance Framework.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["purposeful innovation", "disciplined innovation"],
    relatedTermSlugs: ["ecosystem", "excellence", "platform", "simplicity"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon013],
    searchKeywords: ["innovation", "experiment", "pilot", "technology", "purpose"],
  },
  {
    identifier: "LEX-COMMITMENT",
    term: "Commitment",
    slug: "commitment",
    letter: "C",
    definition:
      "A deliberate institutional promise — public or internal — that shall be truthful, fulfilable, and honoured faithfully.",
    paragraphs: [
      "Every commitment reflects upon the reputation of the entire ecosystem.",
      "Material external commitments shall be recorded in the Commitment Registry.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["promise", "pledge", "guarantee", "institutional word"],
    relatedTermSlugs: ["trust", "truth", "excellence"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon014],
    searchKeywords: ["commitment", "promise", "credibility", "SLA", "fulfilment"],
  },
  {
    identifier: "LEX-ACCOUNTABILITY",
    term: "Accountability",
    slug: "accountability",
    letter: "A",
    definition:
      "The institutional discipline of acknowledging decisions, accepting appropriate responsibility, and learning systematically from failure.",
    paragraphs: [
      "Accountability strengthens institutions; avoiding responsibility weakens them.",
      "Significant incidents shall produce Incident Knowledge Objects and feed the Lessons Learned Repository.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["responsible action", "institutional accountability"],
    relatedTermSlugs: ["trust", "truth", "learning", "commitment"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon015],
    searchKeywords: ["accountability", "incident", "resilience", "root cause", "blameless"],
  },
  {
    identifier: "LEX-STRENGTH",
    term: "Institutional Strength",
    slug: "institutional-strength",
    letter: "I",
    definition:
      "The accumulated capability, resilience, trust, knowledge and service of an institution — measured by how strong it becomes, not merely how large.",
    paragraphs: [
      "Size is temporary. Strength endures.",
      "Every significant decision shall seek to strengthen the institution before it seeks to enlarge it.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["institutional capability", "organizational strength", "resilience"],
    relatedTermSlugs: ["ecosystem", "excellence", "stewardship", "trust"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon016],
    searchKeywords: ["strength", "growth", "capability", "resilience", "acquisition", "ISA"],
  },
  {
    identifier: "LEX-UNCERTAINTY",
    term: "Uncertainty",
    slug: "uncertainty",
    letter: "U",
    definition:
      "The doubt, risk, or information gap that prevents confident action — the domain Stankings Group seeks to reduce through trusted institutions.",
    paragraphs: [
      "The institution shall not promise certainty where certainty is impossible.",
      "It shall increase confidence through truth, verification, transparency, and trust.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["doubt", "risk", "information gap", "anxiety"],
    relatedTermSlugs: ["trust", "truth", "confidence", "verification"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon017],
    searchKeywords: ["uncertainty", "confidence", "doubt", "URF", "reduce uncertainty"],
  },
  {
    identifier: "LEX-CONFIDENCE",
    term: "Confidence",
    slug: "confidence",
    letter: "C",
    definition:
      "The informed assurance that enables people to act, invest, trust, and plan — created when unnecessary uncertainty is responsibly reduced.",
    paragraphs: [
      "Confidence enables progress. It is the real product of the Stankings ecosystem.",
      "Confidence is created when people understand both opportunities and risks.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["assurance", "informed trust", "clarity"],
    relatedTermSlugs: ["uncertainty", "trust", "verification"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon017],
    searchKeywords: ["confidence", "assurance", "trust", "certainty", "progress"],
  },
  {
    identifier: "LEX-PRINCIPLE",
    term: "Principle",
    slug: "principle",
    letter: "P",
    definition:
      "A non-negotiable institutional standard derived from Volume 0 Canons and the Constitution — protected even when opportunity demands compromise.",
    paragraphs: [
      "Opportunities are temporary. Principles endure.",
      "When the two conflict, principles shall guide the institution.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["institutional standard", "foundational commitment", "canon law"],
    relatedTermSlugs: ["trust", "truth", "stewardship", "commitment"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon018],
    searchKeywords: ["principle", "PAR", "compromise", "opportunity", "canon 018"],
  },
  {
    identifier: "LEX-IMPROVEMENT",
    term: "Improvement",
    slug: "improvement",
    letter: "I",
    definition:
      "Responsible strengthening of the institution, its people, systems, or communities — the measure of stewardship across generations.",
    paragraphs: [
      "Stewardship is measured not by preservation alone, but by responsible improvement.",
      "Every generation shall leave the institution stronger than it inherited it.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["strengthening", "maturation", "compounding", "progress"],
    relatedTermSlugs: ["stewardship", "learning", "excellence", "custodian"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon019],
    searchKeywords: ["improvement", "IIR", "stewardship", "ASR", "canon 019", "legacy"],
  },
  {
    identifier: "LEX-JUDGMENT",
    term: "Judgment",
    slug: "judgment",
    letter: "J",
    definition:
      "The disciplined application of institutional principles to changing circumstances — balancing evidence, context, humility, and action.",
    paragraphs: [
      "Policies guide decisions. Canons shape thinking. Judgment determines how principles are applied.",
      "Technology and automation shall support judgment; they shall not replace accountability.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["discernment", "wisdom", "reasoned decision", "sound judgment"],
    relatedTermSlugs: ["truth", "trust", "stewardship", "learning"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon020],
    searchKeywords: ["judgment", "IDI", "wisdom", "reasoning", "canon 020", "decision intelligence"],
  },
  {
    identifier: "LEX-KNOWLEDGE",
    term: "Knowledge",
    slug: "knowledge",
    letter: "K",
    definition:
      "Institutional capability preserved, improved, and shared — an asset deserving the same care as capital, technology, and infrastructure.",
    paragraphs: [
      "Individuals contribute knowledge. The institution preserves it. Future generations build upon it.",
      "Knowledge lost is institutional capability diminished.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["institutional wisdom", "organizational memory", "documented experience"],
    relatedTermSlugs: ["learning", "stewardship", "truth", "judgment"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon021],
    searchKeywords: ["knowledge", "IKG", "library", "asset", "canon 021", "institutional memory"],
  },
  {
    identifier: "LEX-HUMILITY",
    term: "Humility",
    slug: "humility",
    letter: "H",
    definition:
      "The institutional discipline of remaining teachable — pursuing excellence with confidence while welcoming better ideas, evidence, and respectful challenge.",
    paragraphs: [
      "Confidence without humility becomes arrogance. Humility without confidence becomes hesitation.",
      "Enduring institutions cultivate both. Truth takes precedence over pride; learning takes precedence over ego.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["intellectual humility", "teachability", "openness to evidence"],
    relatedTermSlugs: ["learning", "truth", "judgment", "stewardship"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon009, SHARED_REFS.canon023],
    searchKeywords: ["humility", "learning", "challenge", "evidence", "canon 023", "KCP"],
  },
  {
    identifier: "LEX-STANDARD",
    term: "Standard",
    slug: "standard",
    letter: "S",
    definition:
      "The professional, ethical and operational level an institution seeks to establish and elevate within its industry — pursued through excellence rather than domination.",
    paragraphs: [
      "An institution should not merely participate in an industry. It should improve it.",
      "Competition through excellence raises expectations for customers, competitors, and society.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["industry standard", "professional benchmark", "elevated expectation"],
    relatedTermSlugs: ["excellence", "trust", "legacy", "improvement"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon008, SHARED_REFS.canon024],
    searchKeywords: ["standard", "industry", "excellence", "ILD", "canon 024", "raise the standard"],
  },
  {
    identifier: "LEX-ENDURANCE",
    term: "Endurance",
    slug: "endurance",
    letter: "E",
    definition:
      "The continuing consequence of responsible stewardship — an institution's deserved right to endure through faithful service, not the automatic result of age.",
    paragraphs: [
      "Longevity alone is not an achievement. Endurance is earned by every generation.",
      "Institutions that survive while abandoning purpose have merely continued to exist.",
    ],
    status: "approved" as const,
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["deserved longevity", "earned endurance", "institutional legitimacy"],
    relatedTermSlugs: ["stewardship", "legacy", "custodian", "institution"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon006, SHARED_REFS.canon025],
    searchKeywords: ["endurance", "worthy", "legitimacy", "CMD", "canon 025", "volume 0"],
  },
  {
    identifier: "LEX-CONTINUOUS-CUSTOMER-STEWARDSHIP",
    term: "Continuous Customer Stewardship",
    slug: "continuous-customer-stewardship",
    letter: "C",
    definition:
      "The commitment to support customers responsibly throughout meaningful stages of their journey rather than limiting engagement to individual transactions.",
    paragraphs: ["The objective is continued value, not dependency."],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["customer journey stewardship", "ongoing customer care"],
    relatedTermSlugs: ["customer", "stewardship", "trust"],
    referencedBy: [SHARED_REFS.ls002],
    searchKeywords: ["customer stewardship", "journey", "value", "transaction"],
  },
  {
    identifier: "LEX-INSTITUTIONAL-REINFORCEMENT",
    term: "Institutional Reinforcement",
    slug: "institutional-reinforcement",
    letter: "I",
    definition:
      "The principle that every institution within Stankings Group should strengthen one or more other institutions within the ecosystem.",
    paragraphs: ["The success of one institution should contribute to the resilience of the whole."],
    status: "approved",
    version: "1.0",
    author: "Stanley Ukeje",
    approver: "Library Council",
    owner: "Library Council",
    approvedAt: "2026-06-27",
    reviewDate: "2031-06-27",
    synonyms: ["ecosystem strengthening", "mutual resilience"],
    relatedTermSlugs: ["ecosystem", "institution", "capability"],
    referencedBy: [SHARED_REFS.ls002, SHARED_REFS.canon005],
    searchKeywords: ["reinforcement", "ecosystem", "resilience", "institutions"],
  },
];

export const STATIC_LEXICON_TERMS: LexiconTerm[] = STATIC_LEXICON_TERM_DRAFTS.map((t) => ({
  ...t,
  versions: approvedVersion(t),
}));

export function getStaticLexiconTerm(slug: string): LexiconTerm | undefined {
  return STATIC_LEXICON_TERMS.find((t) => t.slug === slug);
}

export function getStaticLexiconTermByIdentifier(
  identifier: string
): LexiconTerm | undefined {
  return STATIC_LEXICON_TERMS.find((t) => t.identifier === identifier);
}

export function getAllStaticLexiconTerms(): LexiconTerm[] {
  return STATIC_LEXICON_TERMS;
}
