import type { LibrarySessionRecord } from "@/lib/library-sessions/types";

export const LIBRARY_SESSIONS: LibrarySessionRecord[] = [
  {
    sessionId: "LIB-2026-06-27-001",
    title: "Transition from Constitutional Drafting to Governance Code",
    date: "2026-06-27",
    summary: [
      "Volume I of the Constitution editorially concluded — Preamble and Articles I–XVII plus The Founder's Charge.",
      "Volume I frozen for Constitutional Convention review — text locked; presentation may strengthen.",
      "Volume II begun — The Governance Code structured as Books, not Articles, to distinguish operational governance from constitutional law.",
      "Book I — Governance Bodies shell created — architecture phase; governance body content withheld per Executive Decision No. 48.",
      "Executive Decision No. 46 adopted — Governance Code subordinate to Constitution.",
    ],
    decisions: [
      "Governance Code shall use Books, not Articles.",
      "Governance Code implements the Constitution and shall never override it.",
      "Each Book completed, audited, and approved before the next Book begins.",
      "Book I defines all governance bodies before Book II details Board operations.",
    ],
    methodology: [
      "Think → Challenge → Design → Approve → Build → Audit → Preserve.",
    ],
    status: "recorded",
  },
  {
    sessionId: "LIB-2026-06-27-002",
    title: "Adoption of Three-Section Session Methodology",
    date: "2026-06-27",
    summary: [
      "Founder and Editor-in-Chief adopted permanent drafting methodology separating discussion, implementation, and institutional memory.",
      "Four alignment questions institutionalized before any feature, company, document, product, or policy is built.",
      "Three Reads Rule adopted: Founder, Engineer, Future Custodian (Year 2126).",
      "Editor's Decision No. 47 — every session produces Editor's Notes, Builder's Notes, Library Session Record, and Progress Report.",
      "Editorial motto adopted: Slow enough to think. Fast enough to build.",
      "Working principle: Nothing leaves the drafting table until both founder and editor are satisfied.",
    ],
    decisions: [
      "No implementation before approval in Builder's Notes.",
      "When either party says 'This feels off…' — stop and investigate.",
      "Institutional question shifts from 'Can we build this?' to 'Should this exist in Stankings Group?'",
      "Library stores history and reasoning, not only documents.",
    ],
    editorDecisionRefs: ["EDITOR-DECISION-47"],
    methodology: [
      "Objective → Scope → Architecture → Draft → Challenge → Approve (documents).",
      "Think → Challenge → Design → Approve → Build → Audit → Preserve (projects).",
    ],
    status: "recorded",
  },
  {
    sessionId: "LIB-2026-06-27-003",
    title: "Editorial Workflow Ratified",
    date: "2026-06-27",
    summary: [
      "Founder and Editor-in-Chief formally adopted a permanent editorial workflow for all Stankings Library publications.",
      "Workflow: Vision → Challenge → Architecture → Approval → Builder's Notes → Implementation → Audit → Library Preservation.",
      "Implementation Readiness Checklist approved — engineering begins only after architectural decisions are complete.",
      "Executive Decision No. 48 adopted — nothing enters the Library without an architecture.",
      "Volume II Governance Code reset to architecture phase — twelve Book shells created; chapter content withheld pending approval.",
      "Editorial Workflow Standard published at FRAMEWORK-EDW-001.",
    ],
    decisions: [
      "Editorial Workflow is a permanent standard under Editorial Standards.",
      "All twelve Governance Code Books exist as planning shells until individually approved.",
      "Book I next session: design architecture — no writing until architecture approved.",
      "Implementation Readiness required before any Builder's Notes reach Cursor.",
    ],
    editorDecisionRefs: ["EDITOR-DECISION-47", "EXECUTIVE-DECISION-48"],
    methodology: [
      "Implementation Readiness: Objective, Scope, No Ambiguity, Dependencies, Acceptance Criteria, Future Compatibility.",
    ],
    status: "recorded",
  },
  {
    sessionId: "LIB-2026-06-27-004",
    title: "Book I Architecture Approved for Review",
    date: "2026-06-27",
    summary: [
      "Editorial team established the architectural framework for Book I of the Governance Code.",
      "Key decision: separate institutional identity (Book I) from operational procedure (Books II–IV).",
      "Book I answers: Who has authority to make which decisions? Later Books answer: How governance is exercised.",
      "Ten-chapter structure proposed — Constitutional Governance Structure through Governance Registers.",
      "Constitutional Council adopted under Option 2 — governance body created under constitutional authority, not a constitutional amendment.",
      "Chapter placeholders created with cross-links. No governance content written.",
    ],
    decisions: [
      "Book I scope: governance bodies only — not meetings, duties, or committee charters.",
      "Constitutional Council is established in the Governance Code under Article authority (Option 2).",
      "Architecture must be formally approved before drafting Chapter 1.",
      "Book I / Book II separation: WHO EXISTS vs HOW THEY WORK.",
    ],
    editorDecisionRefs: ["EXECUTIVE-DECISION-48"],
    methodology: [
      "We do not write until the architecture is approved.",
    ],
    status: "recorded",
  },
  {
    sessionId: "LIB-2026-06-27-005",
    title: "Governance Architecture Refined",
    date: "2026-06-27",
    summary: [
      "Founder approved Constitutional Council as governance body under Governance Code — Editorial Decision No. 49.",
      "Book I architecture refined: Book → Book Charter → Parts → Chapters → Sections.",
      "Four Parts adopted: Governance Foundations, Governance Authorities, Governance Support, Governance Framework.",
      "Ten chapters reordered — Governance Principles moved to Part I; Constitutional Council to Part III.",
      "Governance Map approved as Book I opening — authority flow plus advisory and oversight bodies.",
      "Book Charter shell created. Architecture locked. Next: draft Book Charter.",
    ],
    decisions: [
      "Editorial Decision No. 49 — Constitutional Council established through Governance Code, not Constitution.",
      "Book hierarchy mirrors Constitution discipline while preserving constitutional vs operational distinction.",
      "Governance Map is not an org chart — changes rarely.",
      "Book Charter is next drafting milestone — not Chapter 1.",
    ],
    editorDecisionRefs: ["EDITOR-DECISION-49", "EXECUTIVE-DECISION-48"],
    methodology: [
      "Constitution defines enduring authority. Governance Code defines bodies that exercise it.",
    ],
    status: "recorded",
  },
  {
    sessionId: "LIB-2026-06-27-006",
    title: "Book I Charter Architecture",
    date: "2026-06-27",
    summary: [
      "Founder and Editor-in-Chief defined the Book Charter problem before any content: orient a new reader in under 15 minutes.",
      "Principle adopted: The Book Charter exists to orient readers, not to govern them.",
      "Nine-section Charter architecture fixed — Purpose through Book Status.",
      "Governance Map positioned as visual anchor before textual Charter sections.",
      "Reading Guide architecture defined for six audiences — paths only, no prose.",
      "Library Publishing Standard adopted for all Books — FRAMEWORK-LPS-001.",
    ],
    decisions: [
      "Book Charter answers: How do I use this Book?",
      "Charter must never read like legislation — navigation guide only.",
      "Library Publishing Standard applies to all future volumes, not Book I alone.",
      "No Charter prose until architecture approved by founder.",
    ],
    editorDecisionRefs: ["FRAMEWORK-LPS-001"],
    methodology: [
      "Book → Book Charter → Parts → Chapters → Sections.",
      "Library hierarchy: Cover → Charter → Map → TOC → Content → Appendices → Sessions → Revisions → Index.",
    ],
    status: "recorded",
  },
  {
    sessionId: "LIB-2026-06-27-007",
    title: "Stankings Library Publishing Standard Established",
    date: "2026-06-27",
    summary: [
      "Founder and Editor-in-Chief established SLPS-001 — permanent publishing framework for every official Library publication.",
      "Editorial Decision No. 50 — transition from document creation to institutional publishing.",
      "Fifteen-section publication structure, publication/chapter/diagram metadata standards, and eight-status lifecycle adopted.",
      "Visual identity requirements codified — Legacy Gold, Obsidian Black, institution first.",
      "Publication Generator created — scaffolds new publications from SLPS-001 by default.",
      "Volume migration registry prepared for existing volumes.",
    ],
    decisions: [
      "SLPS-001 applies to all official publications unless approved exception recorded.",
      "FRAMEWORK-LPS-001 superseded by FRAMEWORK-SLPS-001 (alias retained).",
      "Every new publication begins with Publication Generator scaffold.",
      "Publishers ask how publications look — not what to write next.",
    ],
    editorDecisionRefs: ["EDITOR-DECISION-50", "FRAMEWORK-SLPS-001"],
    methodology: [
      "Publishing constitution for the institution — consistency is institutional trust.",
    ],
    status: "recorded",
  },
  {
    sessionId: "LIB-2026-06-27-008",
    title: "Publishing System Approved",
    date: "2026-06-27",
    summary: [
      "Founder and Editor-in-Chief approved SLPS-CORE — the publishing engine that enforces SLPS-001.",
      "Editorial Decision No. 51 — separates publishing rules from the software system that enforces them.",
      "Seven modules established: Generator, Metadata, Cross-Reference, Review, Publishing, Search, Institutional AI.",
      "Platform architecture frozen — no new platform features unless they unblock real publishing work.",
      "Library architected as managed publishing platform with structured metadata, review workflows, and future AI.",
    ],
    decisions: [
      "SLPS-CORE enforces SLPS-001 across every present and future publication.",
      "Every publication originates from Publication Generator with system-managed metadata.",
      "Cross-references generated automatically where possible.",
      "Platform freeze — next session returns to writing the books.",
    ],
    editorDecisionRefs: ["EDITOR-DECISION-51", "FRAMEWORK-SLPS-CORE-001"],
    methodology: [
      "Stop being software builders. Become an institution that publishes knowledge.",
    ],
    status: "recorded",
  },
  {
    sessionId: "LIB-2026-06-27-009",
    title: "Book I Charter Approved for Drafting",
    date: "2026-06-27",
    summary: [
      "Founder and Editor-in-Chief finalized Book I Charter architecture — ten sections including Success Criteria.",
      "Editorial Decision No. 52 — every publication answers three questions in its first five pages.",
      "Book Charter confirmed as orientation document, not governance instrument.",
      "Book Charter v1.0 drafted — Purpose through Success Criteria, Governance Map embedded, cross-links active.",
      "Permanent ten-section Book Charter template established for all Governance Code Books.",
    ],
    decisions: [
      "Book Charter architecture approved — ten sections permanent template.",
      "Section 10 — Success Criteria establishes measurable Book completion standards.",
      "Book Charter v1.0 ready for editorial review.",
      "Chapter drafting waits on Charter approval.",
    ],
    editorDecisionRefs: ["EDITOR-DECISION-52", "BOOK-I-CHARTER"],
    methodology: [
      "The front door, not the living room — orient before you govern.",
      "Why does this exist? How should it be used? How does it relate to the Library?",
    ],
    status: "recorded",
  },
  {
    sessionId: "LIB-2026-06-27-010",
    title: "Foundational Charter Adopted",
    date: "2026-06-27",
    summary: [
      "Founder and Editor-in-Chief renamed Book Charter to Foundational Charter — permanent publishing standard.",
      "Editorial Decision No. 53 — governing introduction to every Book in the Stankings Library.",
      "Three permanent writing principles adopted: Explain Before You Define, Orient Before You Instruct, Principles Before Procedures.",
      "Four chapter approval tests established: Constitution, Implementation, Education, Longevity.",
      "Section 9 renamed Publication Status. Legacy Book Charter references migrated globally.",
      "FRAMEWORK-FC-001 — Foundational Charter Standard published.",
    ],
    decisions: [
      "Foundational Charter replaces Book Charter across SLPS-001, SLPS-CORE, Generator, navigation, and metadata.",
      "Ten-section template locked unless Publishing Standard changes.",
      "Writing rules and chapter tests are permanent editorial law.",
      "Ready to finalize Foundational Charter v1.0 for founder approval.",
    ],
    editorDecisionRefs: ["EDITOR-DECISION-53", "FRAMEWORK-FC-001"],
    methodology: [
      "The first page of Volume II sets the tone for every publication that follows.",
      "Every word must justify its existence.",
    ],
    status: "recorded",
  },
  {
    sessionId: "LIB-2026-06-27-011",
    title: "First Published Draft of the Foundational Charter",
    date: "2026-06-27",
    summary: [
      "Founder and Editor-in-Chief completed the first full draft of the Foundational Charter for Volume II, Book I.",
      "First substantive governance publication under SLPS-001 and the Editorial Workflow Standard.",
      "Charter establishes purpose, scope, authority and navigation without operational governance rules.",
      "Ten versioned sections with interactive Governance Map and active cross-references.",
      "v1.0 RC1 submitted for Founder Review.",
    ],
    decisions: [
      "Foundational Charter v1.0 RC1 submitted for Founder Review.",
      "Chapter 1 drafting begins after charter revision and approval.",
      "Architectural separation preserved: identity in Book I, procedures in later Books.",
    ],
    editorDecisionRefs: ["BOOK-I-FOUNDATIONAL-CHARTER", "FRAMEWORK-SLPS-001", "FRAMEWORK-EDW-001"],
    methodology: [
      "Not grand. Not complicated. Just clear.",
      "Orient the reader like walking into headquarters for the first time.",
    ],
    status: "recorded",
  },
  {
    sessionId: "LIB-2026-06-27-012",
    title: "Chapter 1 Architecture — Constitutional Governance Structure",
    date: "2026-06-27",
    summary: [
      "Founder and Editor-in-Chief established the architectural framework for Chapter 1 of Book I.",
      "Chapter explains origin, flow and purpose of governance without operational procedures.",
      "Eight sections with three diagram scaffolds and CEF-001 education footer adopted for all chapters.",
      "Architecture proposed — awaiting Founder approval before prose drafting.",
    ],
    decisions: [
      "Chapter 1 architecture proposed with eight sections.",
      "CEF-001 Chapter Education Standard adopted — every chapter is governance and teaching.",
      "Section 1 drafting begins after Founder approval of architecture.",
    ],
    editorDecisionRefs: ["FRAMEWORK-CEF-001", "BOOK-I-CH-01-ARCHITECTURE"],
    methodology: [
      "Design before draft. Chapter 1 becomes the foundation for every governance decision.",
      "Architecture precedes prose.",
    ],
    status: "recorded",
  },
  {
    sessionId: "LIB-2026-07-03-013",
    title: "Founder Sustainability Insight",
    date: "2026-07-03",
    summary: [
      "The Founder reflected on completing multiple client engagements that generated meaningful income while continuing to build the Stankings Group ecosystem.",
      "Income was used primarily to strengthen household welfare.",
      "Session highlighted sustainable personal and family welfare alongside long-term institutional development.",
      "FOUNDER-INSIGHT-001 created — short-term cash flow and long-term institution building as complementary engines.",
    ],
    decisions: [
      "Recorded as institutional learning — FOUNDER-INSIGHT-001 Sustainable Stewardship.",
      "Linked to stewardship Canons and Custodian Programme case study CS-FND-001.",
    ],
    editorDecisionRefs: ["FOUNDER-INSIGHT-001", "CANON-004", "CANON-006"],
    methodology: [
      "A strong institution is built on sustainable stewardship, not constant sacrifice.",
      "The principle applies to the founder as much as the organization.",
    ],
    status: "recorded",
  },
];

export function getLibrarySession(sessionId: string): LibrarySessionRecord | undefined {
  return LIBRARY_SESSIONS.find((s) => s.sessionId === sessionId);
}
