/**
 * Volume II — Book shells (architecture only)
 * No chapter content until editorial approval — Executive Decision No. 48
 */

import type { GovernanceBook, GovernanceBookChapter } from "@/lib/governance-code/types";
import {
  BOOK_I_CENTRAL_QUESTION,
  BOOK_I_SCOPE_EXCLUDES,
  BOOK_I_SCOPE_INCLUDES,
  CONSTITUTIONAL_COUNCIL_PRINCIPLE,
  getBookIChapterSummaries,
} from "@/lib/governance-code/books/book-i/chapters";

function chapters(bookId: string, titles: string[]): GovernanceBookChapter[] {
  return titles.map((title, i) => {
    const num = i + 1;
    const id = `${bookId}-ch-${String(num).padStart(2, "0")}`;
    return {
      id,
      chapter: `Chapter ${num}`,
      title,
      status: "planned" as const,
      href:
        bookId === "book-i"
          ? `/library/governance-code/book-i/chapters/${id}`
          : `/library/governance-code/${bookId}`,
    };
  });
}

const VOLUME_II_KO: GovernanceBook["knowledgeObjectRefs"] = [
  {
    identifier: "VOLUME-II-GOVERNANCE-CODE",
    title: "Volume II — Governance Code",
    href: "/library/governance-code",
  },
  {
    identifier: "FRAMEWORK-GC-001",
    title: "Governance Code Portal",
    href: "/library/frameworks/governance-code-portal",
  },
];

const SHARED_SESSIONS: GovernanceBook["sessionHistory"] = [
  {
    sessionId: "LIB-2026-06-27-001",
    title: "Transition from Constitutional Drafting to Governance Code",
    href: "/library/sessions/LIB-2026-06-27-001",
    date: "2026-06-27",
  },
];

const ARTICLES_IV_XVI = [
  "CONSTITUTION-ARTICLE-IV",
  "CONSTITUTION-ARTICLE-V",
  "CONSTITUTION-ARTICLE-VI",
  "CONSTITUTION-ARTICLE-VII",
  "CONSTITUTION-ARTICLE-VIII",
  "CONSTITUTION-ARTICLE-IX",
  "CONSTITUTION-ARTICLE-X",
  "CONSTITUTION-ARTICLE-XI",
  "CONSTITUTION-ARTICLE-XII",
  "CONSTITUTION-ARTICLE-XIII",
  "CONSTITUTION-ARTICLE-XIV",
  "CONSTITUTION-ARTICLE-XV",
  "CONSTITUTION-ARTICLE-XVI",
] as const;

export const GOVERNANCE_CODE_BOOKS: GovernanceBook[] = [
  {
    id: "book-i",
    book: "Book I",
    title: "Governance Bodies",
    status: "architecture_locked",
    locked: true,
    href: "/library/governance-code/book-i",
    overview: `Book I answers one question: ${BOOK_I_CENTRAL_QUESTION} It defines who governs — not how governance is exercised.`,
    purpose:
      "Define what governance bodies exist — identity, authority, and relationships. Book → Foundational Charter → Parts → Chapters → Sections.",
    description:
      "Who has authority to make which decisions? Governance bodies only — not meetings, duties, or committee charters.",
    chapters: getBookIChapterSummaries(),
    builderNotes: [
      `Central question: ${BOOK_I_CENTRAL_QUESTION}`,
      `Scope: ${BOOK_I_SCOPE_INCLUDES}`,
      `Excludes: ${BOOK_I_SCOPE_EXCLUDES.join("; ")}.`,
      "Four Parts, ten Chapters — architecture locked. Foundational Charter v1.0 drafted (ten sections).",
      "Foundational Charter v1.0 RC1 — editorial review. Chapter 1 architecture proposed (Session 012).",
      CONSTITUTIONAL_COUNCIL_PRINCIPLE,
      "Book I must be complete before Book II (Board Operations) begins.",
    ],
    sessionHistory: [
      ...SHARED_SESSIONS,
      {
        sessionId: "LIB-2026-06-27-003",
        title: "Editorial Workflow Ratified",
        href: "/library/sessions/LIB-2026-06-27-003",
        date: "2026-06-27",
      },
      {
        sessionId: "LIB-2026-06-27-004",
        title: "Book I Architecture Approved for Review",
        href: "/library/sessions/LIB-2026-06-27-004",
        date: "2026-06-27",
      },
      {
        sessionId: "LIB-2026-06-27-005",
        title: "Governance Architecture Refined",
        href: "/library/sessions/LIB-2026-06-27-005",
        date: "2026-06-27",
      },
      {
        sessionId: "LIB-2026-06-27-010",
        title: "Foundational Charter Adopted",
        href: "/library/sessions/LIB-2026-06-27-010",
        date: "2026-06-27",
      },
    ],
    reviewHistory: [
      {
        date: "2026-06-27",
        phase: "Architecture Locked",
        note: "Four Parts adopted. Book Charter shell. Constitutional Council under Editorial Decision No. 49. Governance Map approved as opening.",
      },
    ],
    constitutionalRefs: [...ARTICLES_IV_XVI] as string[],
    canonRefs: ["CANON-002", "CANON-004", "CANON-016", "CANON-020", "CANON-021"],
    knowledgeObjectRefs: [
      ...VOLUME_II_KO,
      {
        identifier: "BOOK-I-ARCHITECTURE",
        title: "Book I Architecture",
        href: "/library/governance-code/book-i",
      },
    ],
  },
  {
    id: "book-ii",
    book: "Book II",
    title: "Board Operations",
    status: "planning",
    locked: true,
    href: "/library/governance-code/book-ii",
    overview: "How the Board of Directors operates — calendar, meetings, papers, decisions, and evaluation.",
    purpose: "Translate Article IV reserved powers into repeatable Board practice.",
    description:
      "How the Board works — calendar, meetings, reserved matters, papers, minutes, and evaluation.",
    chapters: chapters("book-ii", [
      "Annual Board Calendar",
      "Meeting Procedures",
      "Emergency Meetings",
      "Quorum",
      "Voting",
      "Reserved Matters",
      "Board Papers",
      "Minutes",
      "Board Evaluations",
      "Executive Sessions",
      "Confidentiality",
      "Strategic Retreats",
    ]),
    builderNotes: ["Placeholder — begins only after Book I architecture approved."],
    sessionHistory: SHARED_SESSIONS,
    reviewHistory: [],
    constitutionalRefs: ["CONSTITUTION-ARTICLE-IV"],
    canonRefs: ["CANON-004"],
    knowledgeObjectRefs: VOLUME_II_KO,
  },
  {
    id: "book-iii",
    book: "Book III",
    title: "Executive Leadership",
    status: "planning",
    locked: true,
    href: "/library/governance-code/book-iii",
    overview: "Group and institutional executive roles — authority, decision limits, delegations, and succession.",
    purpose: "Define how executive leadership implements constitutional stewardship in daily practice.",
    description:
      "Group and institutional executive roles — purpose, authority, decision limits, delegations, and succession.",
    chapters: chapters("book-iii", [
      "Group CEO",
      "CFO",
      "CTO",
      "COO",
      "General Counsel",
      "Chief Knowledge Officer",
      "Chief Risk Officer",
      "Heads of Institutions",
    ]),
    builderNotes: ["Placeholder — subordinate to Book I governance body definitions."],
    sessionHistory: SHARED_SESSIONS,
    reviewHistory: [],
    constitutionalRefs: ["CONSTITUTION-ARTICLE-V", "CONSTITUTION-ARTICLE-VI"],
    canonRefs: ["CANON-004", "CANON-020"],
    knowledgeObjectRefs: VOLUME_II_KO,
  },
  {
    id: "book-iv",
    book: "Book IV",
    title: "Governance Committees",
    status: "planning",
    locked: true,
    href: "/library/governance-code/book-iv",
    overview: "Committee charters — scope, authority, composition, and reporting for each governance committee.",
    purpose: "Operationalise committee governance without duplicating Book I body definitions.",
    description: "Committee charters — audit, risk, cybersecurity, technology, AI, innovation, ethics, and more.",
    chapters: chapters("book-iv", [
      "Audit",
      "Risk",
      "Cybersecurity",
      "Technology",
      "AI",
      "Innovation",
      "Procurement",
      "Ethics",
      "Governance",
      "Library",
      "Investment",
      "Compensation",
    ]),
    builderNotes: ["Placeholder — committee charters reference Book I bodies."],
    sessionHistory: SHARED_SESSIONS,
    reviewHistory: [],
    constitutionalRefs: ["CONSTITUTION-ARTICLE-IV"],
    canonRefs: ["CANON-004"],
    knowledgeObjectRefs: VOLUME_II_KO,
  },
  {
    id: "book-v",
    book: "Book V",
    title: "Decision Governance",
    status: "planning",
    locked: true,
    href: "/library/governance-code/book-v",
    overview: "Structured decision proposals — evidence, assessments, and constitutional alignment.",
    purpose: "Implement Article VI Institutional Decision Register in operational practice.",
    description:
      "Practical implementation of Article VI — structured proposals, evidence, and constitutional alignment.",
    chapters: chapters("book-v", [
      "Executive Summary",
      "Problem Statement",
      "Options Considered",
      "Evidence",
      "Trust Impact Assessment",
      "Risk Assessment",
      "Financial Assessment",
      "Legal Review",
      "Technology Review",
      "Canon References",
      "Constitutional References",
      "Recommendation",
    ]),
    builderNotes: ["Placeholder — integrates FRAMEWORK-CDW-001 and IDR discipline."],
    sessionHistory: SHARED_SESSIONS,
    reviewHistory: [],
    constitutionalRefs: ["CONSTITUTION-ARTICLE-VI"],
    canonRefs: ["CANON-007", "CANON-020"],
    knowledgeObjectRefs: [
      ...VOLUME_II_KO,
      {
        identifier: "FRAMEWORK-CDW-001",
        title: "Constitutional Decision Workspace",
        href: "/library/frameworks/constitutional-decision-workspace",
      },
    ],
  },
  {
    id: "book-vi",
    book: "Book VI",
    title: "Risk & Assurance",
    status: "planning",
    locked: true,
    href: "/library/governance-code/book-vi",
    overview: "Enterprise, operational, cyber, legal, reputational, and AI risk — plus assurance and crisis response.",
    purpose: "Treat risk as stewardship, not compliance theatre.",
    description: "Risk as stewardship — enterprise, cyber, operational, legal, reputational, AI, and crisis management.",
    chapters: chapters("book-vi", [
      "Enterprise Risk",
      "Cyber Risk",
      "Operational Risk",
      "Legal Risk",
      "Reputational Risk",
      "AI Risk",
      "Third-Party Risk",
      "Crisis Management",
      "Business Continuity",
      "Disaster Recovery",
    ]),
    builderNotes: ["Placeholder — links to Constitutional Health Dashboard reporting."],
    sessionHistory: SHARED_SESSIONS,
    reviewHistory: [],
    constitutionalRefs: ["CONSTITUTION-ARTICLE-VII", "CONSTITUTION-ARTICLE-XIV"],
    canonRefs: ["CANON-015", "CANON-016"],
    knowledgeObjectRefs: VOLUME_II_KO,
  },
  {
    id: "book-vii",
    book: "Book VII",
    title: "Financial Stewardship",
    status: "planning",
    locked: true,
    href: "/library/governance-code/book-vii",
    overview: "Capital allocation, treasury, controls, escrow, and internal audit — money as fuel, not purpose.",
    purpose: "Govern financial stewardship in alignment with Articles VII and VIII.",
    description: "Money is fuel, not purpose — capital allocation, treasury, escrow, controls, and internal audit.",
    chapters: chapters("book-vii", [
      "Capital Allocation",
      "Investment Principles",
      "Treasury",
      "Reserves",
      "Escrow Governance",
      "Budgeting",
      "Procurement",
      "Asset Protection",
      "Financial Controls",
      "Internal Audit",
    ]),
    builderNotes: ["Placeholder — integrates Institutional Asset Register."],
    sessionHistory: SHARED_SESSIONS,
    reviewHistory: [],
    constitutionalRefs: ["CONSTITUTION-ARTICLE-VII", "CONSTITUTION-ARTICLE-VIII"],
    canonRefs: ["CANON-002", "CANON-014"],
    knowledgeObjectRefs: [
      ...VOLUME_II_KO,
      {
        identifier: "FRAMEWORK-IAR-001",
        title: "Institutional Asset Registry",
        href: "/library/frameworks/institutional-asset-registry",
      },
    ],
  },
  {
    id: "book-viii",
    book: "Book VIII",
    title: "Technology Governance",
    status: "planning",
    locked: true,
    href: "/library/governance-code/book-viii",
    overview: "Software, AI, infrastructure, security, data, identity, and architecture decision governance.",
    purpose: "Ensure technology decisions strengthen trust and constitutional alignment.",
    description: "Software, AI, infrastructure, APIs, security, cloud, data, identity, and architecture decisions.",
    chapters: chapters("book-viii", [
      "Software Standards",
      "AI Governance",
      "Infrastructure",
      "APIs",
      "Source Code",
      "Security",
      "Cloud",
      "Data",
      "Identity",
      "Engineering Reviews",
      "Architecture Decisions",
    ]),
    builderNotes: ["Placeholder — subordinate to Engineering Standards (future volume)."],
    sessionHistory: SHARED_SESSIONS,
    reviewHistory: [],
    constitutionalRefs: ["CONSTITUTION-ARTICLE-XII", "CONSTITUTION-ARTICLE-XIII"],
    canonRefs: ["CANON-011", "CANON-012", "CANON-023"],
    knowledgeObjectRefs: VOLUME_II_KO,
  },
  {
    id: "book-ix",
    book: "Book IX",
    title: "People & Culture",
    status: "planning",
    locked: true,
    href: "/library/governance-code/book-ix",
    overview: "Recruitment, performance, mentorship, learning, recognition, and institutional culture.",
    purpose: "Govern people practices as stewardship of institutional character.",
    description: "Institutional culture — recruitment, performance, mentorship, learning, and discipline.",
    chapters: chapters("book-ix", [
      "Recruitment",
      "Performance",
      "Leadership",
      "Mentorship",
      "Learning",
      "Diversity of Expertise",
      "Professional Development",
      "Recognition",
      "Discipline",
      "Wellbeing",
    ]),
    builderNotes: ["Placeholder — links to Custodian Programme and leadership frameworks."],
    sessionHistory: SHARED_SESSIONS,
    reviewHistory: [],
    constitutionalRefs: ["CONSTITUTION-ARTICLE-V", "CONSTITUTION-ARTICLE-XVI"],
    canonRefs: ["CANON-004", "CANON-025"],
    knowledgeObjectRefs: VOLUME_II_KO,
  },
  {
    id: "book-x",
    book: "Book X",
    title: "Innovation Governance",
    status: "planning",
    locked: true,
    href: "/library/governance-code/book-x",
    overview: "Venture pipeline, incubation, spin-offs, IP, and constitutional innovation review.",
    purpose: "Implement Article X innovation discipline — fair consideration, not entitlement.",
    description: "Venture Studio, idea pipeline, incubation, spin-offs, and intellectual property.",
    chapters: chapters("book-x", [
      "Idea Pipeline",
      "Family Innovation",
      "Employee Innovation",
      "Research",
      "Prototype Funding",
      "Venture Review",
      "Incubation",
      "Spin-offs",
      "Intellectual Property",
      "Commercialization",
    ]),
    builderNotes: ["Placeholder — integrates Innovation Portal (Schedule H)."],
    sessionHistory: SHARED_SESSIONS,
    reviewHistory: [],
    constitutionalRefs: ["CONSTITUTION-ARTICLE-X", "CONSTITUTION-ARTICLE-II"],
    canonRefs: ["CANON-003", "CANON-013"],
    knowledgeObjectRefs: [
      ...VOLUME_II_KO,
      {
        identifier: "FRAMEWORK-INP-001",
        title: "Innovation Portal",
        href: "/library/frameworks/innovation-portal",
      },
    ],
  },
  {
    id: "book-xi",
    book: "Book XI",
    title: "Knowledge Governance",
    status: "planning",
    locked: true,
    href: "/library/governance-code/book-xi",
    overview: "The Library, knowledge objects, publications, standards, and institutional history.",
    purpose: "Operationalise Article XIII knowledge governance in daily practice.",
    description: "The Library, knowledge objects, publications, commentary, standards, and institutional history.",
    chapters: chapters("book-xi", [
      "The Library",
      "Knowledge Objects",
      "Publications",
      "Documentation",
      "Commentary",
      "Engineering Standards",
      "Research",
      "AI Knowledge",
      "Institutional History",
    ]),
    builderNotes: ["Placeholder — integrates Stankings Library Portal and session records."],
    sessionHistory: [
      ...SHARED_SESSIONS,
      {
        sessionId: "LIB-2026-06-27-002",
        title: "Adoption of Three-Section Session Methodology",
        href: "/library/sessions/LIB-2026-06-27-002",
        date: "2026-06-27",
      },
      {
        sessionId: "LIB-2026-06-27-003",
        title: "Editorial Workflow Ratified",
        href: "/library/sessions/LIB-2026-06-27-003",
        date: "2026-06-27",
      },
    ],
    reviewHistory: [],
    constitutionalRefs: ["CONSTITUTION-ARTICLE-XIII"],
    canonRefs: ["CANON-021", "CANON-023"],
    knowledgeObjectRefs: [
      ...VOLUME_II_KO,
      {
        identifier: "FRAMEWORK-SLP-001",
        title: "Stankings Library Portal",
        href: "/library/frameworks/stankings-library-portal",
      },
      {
        identifier: "FRAMEWORK-LIB-SESS-001",
        title: "Library Session Records",
        href: "/library/sessions",
      },
    ],
  },
  {
    id: "book-xii",
    book: "Book XII",
    title: "Reporting & Assurance",
    status: "planning",
    locked: true,
    href: "/library/governance-code/book-xii",
    overview: "Every recurring institutional report — stewardship, health, trust, risk, knowledge, and AI.",
    purpose: "Ensure accountability through disciplined reporting, not performative disclosure.",
    description: "Every recurring report — stewardship, health, trust, innovation, cyber, knowledge, risk, and AI.",
    chapters: chapters("book-xii", [
      "Annual Stewardship Report",
      "Constitutional Health Report",
      "Trust Report",
      "Innovation Report",
      "Cybersecurity Report",
      "Knowledge Report",
      "Risk Report",
      "AI Governance Report",
      "Institutional Review Report",
    ]),
    builderNotes: ["Placeholder — integrates Constitutional Health Dashboard."],
    sessionHistory: SHARED_SESSIONS,
    reviewHistory: [],
    constitutionalRefs: ["CONSTITUTION-ARTICLE-XIV", "CONSTITUTION-ARTICLE-XV"],
    canonRefs: ["CANON-019", "CANON-022"],
    knowledgeObjectRefs: [
      ...VOLUME_II_KO,
      {
        identifier: "FRAMEWORK-CHD-001",
        title: "Constitutional Health Dashboard",
        href: "/library/frameworks/constitutional-health-dashboard",
      },
    ],
  },
];

export function getGovernanceBook(id: string): GovernanceBook | undefined {
  return GOVERNANCE_CODE_BOOKS.find((b) => b.id === id);
}

export function getGovernanceBookStats() {
  const total = GOVERNANCE_CODE_BOOKS.length;
  const planning = GOVERNANCE_CODE_BOOKS.filter((b) => b.status === "planning").length;
  const drafting = GOVERNANCE_CODE_BOOKS.filter((b) => b.status === "drafting").length;
  const chapters = GOVERNANCE_CODE_BOOKS.reduce((n, b) => n + b.chapters.length, 0);
  return { total, planning, drafting, chapters };
}
